### PR TITLE
Fix "Not implemented" exception with macros

### LINKED ISSUE #5974: Exception in Hostfunction: not implemented
### Description

Screenshot 2024-05-05 at 12 00 10 AM

this error produce after installation of the app

### Steps to reproduce

Add library to package.json file
run yarn
pod install
install app

### Snack or a link to a repository

I have problem in my project

### Reanimated version

3.8.1

### React Native version

0.73.0

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by tjzel**
Supersedes 🚽 #6028

Fixes #5974

### CODE REVIEW

File: packages/react-native-reanimated/Common/cpp/SharedItems/Shareables.h [hunk 1]
```diff
@@ -183,16 +183,20 @@ class ShareableObject : public Shareable {
  public:
   ShareableObject(jsi::Runtime &rt, const jsi::Object &object);
 
+#if defined(USE_HERMES) || REACT_NATIVE_MINOR_VERSION >= 74
```
Comment (tomekzaw) [inline packages/react-native-reanimated/Common/cpp/SharedItems/Shareables.h:186]: Let's add
```
#define SUPPORTS_NATIVE_STATE (defined(USE_HERMES) || REACT_NATIVE_MINOR_VERSION >= 74)
```
in `Shareable.h`
and use `#if SUPPORTS_NATIVE_STATE` everywhere else.

Comment (piaskowyk) [reply packages/react-native-reanimated/Common/cpp/SharedItems/Shareables.h:186]: +1 for this change

Apart from it, the rest is ok 👍

Comment (tjzel) [reply packages/react-native-reanimated/Common/cpp/SharedItems/Shareables.h]: You got it @tomekzaw @piaskowyk 👍

**Review by tomekzaw — APPROVED** [review]

**Review by piaskowyk — APPROVED** [review]
