### PR TITLE
Fix animatedRef on Fabric

### LINKED ISSUE #4256: 3.0.2 Android Cannot read property 'stateNode' of undefined
### Description

if an animated component has a ref provided by useAnimatedRef hook, it will produce this undefined error, even though fabric is enabled.

### Steps to reproduce

1. create react-native app by react-native-cli with latest stable version
2. enable new arch 
3. create an animate component in app.tsx and then give it a ref provide by useAnimatedRef hook

### Snack or a link to a repository

https://github.com/fine0813/reanimated-crash

### Reanimated version

3.0.2

### React Native version

0.71.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by mstach60161**
## Summary

- Fixes #4256

### Problem

If the scrollable component is not root, UI `scrollTo` doesn't work on Fabric.

#4384 - It was fixed here for Paper, but after this change app crashes on Fabric, because `getScrollableNode` in both architectures returns viewTag as a number, not component. It's working for Paper, because we are passing either component or number to `findNodeHandle` method, but on Fabric we need component ref.

### Fix
 
Instead of `getScrollableNode`, we can use `getNativeScrollRef` and get scrollable reference. 

### TODO

Unfortunately this method is not implemented yet for `Flash-list` -> https://shopify.github.io/flash-list/docs/usage#:~:text=Unsupported%20methods%3A
so for now, UI `scrollTo` on FlashList works only for Paper Architecture.

## Test plan

ScrollToExample:

- Paper, ScrollView
- Paper, FlatList
- Fabric, ScrollView
- Fabric, FlatList

### CODE REVIEW

File: src/reanimated2/hook/useAnimatedRef.ts [hunk 1]
```diff
@@ -19,6 +20,23 @@ function getShareableShadowNodeFromComponent(
   return getShadowNodeWrapperFromHostInstance(component);
 }
 
+function getScrollableRef(component: ComponentRef): ComponentRef {
+  if (global._IS_FABRIC) {
+    if (component.getNativeScrollRef) {
+      return component.getNativeScrollRef();
+    } else {
+      console.warn(
+        'this component has no implemented `getScrollableNode` method. Please report this issue to the library maintainers.'
```
Comment (tomekzaw) [inline src/reanimated2/hook/useAnimatedRef.ts:29]:
```suggestion
        '[Reanimated] ${Component.displayName || Component.name || 'Component'} has no implemented `getNativeScrollRef` method. Please report this issue to the library maintainers.'
```

File: src/reanimated2/hook/useAnimatedRef.ts [hunk 2]
```diff
@@ -31,11 +49,7 @@ export function useAnimatedRef<T extends ComponentRef>(): RefObjectFunction<T> {
     const fun: RefObjectFunction<T> = <RefObjectFunction<T>>((component) => {
       // enters when ref is set by attaching to a component
       if (component) {
-        tag.value = getTagValueFunction(
-          component.getScrollableNode
-            ? component.getScrollableNode()
-            : component
-        );
+        tag.value = getTagValueFunction(getScrollableRef(component));
```
Comment (tomekzaw) [inline src/reanimated2/hook/useAnimatedRef.ts:52]: Can we also use `getScrollableRef` in `useAnimatedRef.ts`?

Comment (mstach60161) [reply src/reanimated2/hook/useAnimatedRef.ts:52]: I'm not sure what do you mean.

File: src/reanimated2/hook/useAnimatedRef.ts [hunk 3]
```diff
@@ -19,6 +22,25 @@ function getShareableShadowNodeFromComponent(
...
+  if (global._IS_FABRIC) {
+    if (component.getNativeScrollRef) {
+      return component.getNativeScrollRef();
+    } else {
+      console.warn(
+        `[Reanimated] ${
+          component.displayName || component.name || 'Component'
+        } has no implemented 'getNativeScrollRef' method. Please report this issue to the library maintainers.`
+      );
+    }
```
Comment (piaskowyk) [inline src/reanimated2/hook/useAnimatedRef.ts:35]: We need to remove this config because we can pass here reference to any object.

File: src/reanimated2/hook/useAnimatedRef.ts [hunk 4]
```diff
@@ -19,6 +22,25 @@ function getShareableShadowNodeFromComponent(
   return getShadowNodeWrapperFromHostInstance(component);
 }
 
+function getScrollableRef(component: ComponentRef): ComponentRef {
```
Comment (piaskowyk) [inline src/reanimated2/hook/useAnimatedRef.ts:25]: getScrollableRef -> getComponentRef

**Review by piaskowyk — COMMENTED** [review]
We need add some comments here, and table with information about which method is used by ScrollView, FlatList and FlashList

File: src/reanimated2/hook/useAnimatedRef.ts (hunk 4 above)
Comment (tomekzaw) [reply src/reanimated2/hook/useAnimatedRef.ts:25]: `getComponentRef` is too generic I think

**Review by piaskowyk — APPROVED** [review]

File: src/reanimated2/hook/useAnimatedRef.ts [hunk 5]
```diff
@@ -10,6 +10,9 @@ import {
 } from '../shareables';
 
 interface ComponentRef extends Component {
+  displayName?: string;
+  name?: string;
```
Comment (tomekzaw) [inline src/reanimated2/hook/useAnimatedRef.ts:14]:
```suggestion
```

**Review by tomekzaw — APPROVED** [review]
👏
