### PR TITLE
Keep non-react views in AnimationManager

### LINKED ISSUE #4306: [Android] `<Animated.ScrollView />` is crashing on `navigate.goBack()` when using `refreshControl` prop
### Description

This issue occurs after I upgraded from v2 to v3 in React Native 0.71.4.

My app keep crashing when I opened a page and pressing back button (or executing `navigation.goBack()`).

I tried to reproduce the issue using bare React Native 0.71.4 project and installed both Reanimated v3 and latest React Navigation.

I found that these props are having weird behavior:
- `Animated.ScrollView.refreshControl`
- `Animated.View.exiting`

Whenever I add `<Animated.ScrollView refreshControl={{....}} />` with children `<Animated.View exiting={...} />` the app is crashing when navigating back.

``` JSX
<Animated.ScrollView
  refreshControl={(
    <RefreshControl refreshing={refreshing} />
  )}
>
  <Animated.View
    entering={ZoomIn}
    exiting={ZoomOut}
  />
</Animated.ScrollView>
```

Tested on Android device and emulator (Android 13, SDK 33). Crashing in both debug and production mode.

### Steps to reproduce

Crash Repro:
1. Clone or download the repo.
2. Run the `yarn android`.
3. In Home page, press "Go to Page A" button.
4. In Page A, press "Check Crash" button or just navigate back using back button.
5. The app crashes.

Not Crashing:
1. In file PageA.tsx, comment one of these prop `refreshControl` or `exiting`
2. Run the app and navigation works normally.

### Snack or a link to a repository

https://github.com/vozaldi/repro-rn-reanimated-crash

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### LINKED ISSUE #4437: ReanimatedError: Exception in HostFunction: java.lang.ClassNotFoundException: Could not retrieve ViewPager2 instance, js engine: reanimated
### Description

See the reproducible GitHub example. When using the LayoutAnimation `exiting` and unmounting the TabView, the following exception occurs: 

`ReanimatedError: Exception in HostFunction: java.lang.ClassNotFoundException: Could not retrieve ViewPager2 instance, js engine: reanimated` 

```
const Route = () => (
  <View style={{flex: 1, backgroundColor: '#673ab7'}}>
    <Animated.View
      entering={FadeIn.duration(250)}
      /* REMOVING exiting={FadeOut.duration(100)} FIXES THE ISSUE */
      exiting={FadeOut.duration(100)}
      style={{backgroundColor: 'green'}}>
      <Text>Number</Text>
    </Animated.View>
  </View>
);

const renderScene = SceneMap({
  first: Route,
});

export default function TabViewExample() {
    const [unmountTabView, setUnmountTabView] = React.useState(false);

    const [index, setIndex] = React.useState(0);
    const [routes] = React.useState([{key: 'first', title: 'First'}]);

    useEffect(() => {
        setTimeout(() => {
            setUnmountTabView(true);
        }, 3000);
    }, []);

    if (!unmountTabView) {
        return (
            <TabView
                navigationState={{index, routes}}
                renderScene={renderScene}
                onIndexChange={setIndex}
            />
        );
    }
    return (
        <View>
            <Text>Completely blank screen</Text>
        </View>
    );
}
```

### Steps to reproduce

1. Download and run repository on Android

### Snack or a link to a repository

https://github.com/ealmiladi/reanimated-exiting-bug

### Reanimated version

3.1.0

### React Native version

0.71.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by Latropos**
## Summary

Removing views with id -1 (views that are not a react-native ones) causes at least two bugs on Android.

Fixes #4306 and Fixes #4437

### Bug https://github.com/software-mansion/react-native-reanimated/issues/4306 - [Android] <Animated.ScrollView /> is crashing on navigate.goBack() when using refreshControl prop

<details><summary> Error log </summary>

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.swmansion.reanimated.example, PID: 14673
    java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)
        at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2099)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4287)
        at android.view.View.draw(View.java:23197)
        at android.view.View.updateDisplayListIfDirty(View.java:22061)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.draw(View.java:23197)
        at android.view.View.updateDisplayListIfDirty(View.java:22061)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
E/AndroidRuntime:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4670)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4381)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3600)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:832)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
</details>
<table>
<tr><td>BEFORE</td><td>AFTER</td></tr>
<tr><td>

https://user-images.githubusercontent.com/56199675/237047814-3f54fef7-b546-44a4-ba6b-a184c39b792e.mov

</td><td>

https://user-images.githubusercontent.com/56199675/237047543-afb5c935-6e2a-4b1d-9c70-42ed1d6ca9ef.mov

</td></tr>
</table>

### Bug https://github.com/software-mansion/react-native-reanimated/issues/4437 - ReanimatedError: Exception in HostFunction: java.lang.ClassNotFoundException: Could not retrieve ViewPager2 instance, js engine: reanimated

No error logs 😢 
<table>
<tr><td>BEFORE</td><td>AFTER</td></tr>
<tr><td>

https://user-images.githubusercontent.com/56199675/237048938-faeea75c-786c-42de-a607-9b681769ee7f.mov

</td><td>

https://user-images.githubusercontent.com/56199675/237048461-1b2c87ee-bb0a-4649-8a20-60b8a4811a93.mov

</td></tr>
</table>

## Test plan

Tested on following repos:
* https://github.com/vozaldi/repro-rn-reanimated-crash
* https://github.com/ealmiladi/reanimated-exiting-bug

### CODE REVIEW

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java [hunk 1]
```diff
@@ -600,6 +600,9 @@ private void maybeDropAncestors(View exitingView) {
 
   private void removeView(View view, @Nullable ViewGroup parent) {
     int tag = view.getId();
+    if (tag == -1) {
+      return;
+    }
```
Comment (piaskowyk) [inline android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:605]: Good job with debugging!
I wondering if we safety can just stop function here, instead of call `mReanimatedNativeHierarchyManager.publicDropView(view);` and `parent.removeView(view);` Can we be sure that this changes will not drove to memory leaks?

**Comment by piaskowyk** [comment]
Could you provide to issue description the source code of reproduction?

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java (hunk 1 above)
Comment (Latropos) [reply android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:605]: I've replaced `return` with your code and tested with `Memory Profiler`. I haven't seen any leaks:
Screenshot 2023-05-16 at 10 24 26

Comment (Latropos) [reply android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java]: I've checked that `mCallbacks.put(tag, callback);` is not called for `tag=-1`

Comment (piaskowyk) [reply android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:605]: I saw that you reverted changes with view removing. Let's try again 😄
Which call causes a crash?
`mReanimatedNativeHierarchyManager.publicDropView(view)` or  `parent.removeView(view)` ?

It seems that mReanimatedNativeHierarchyManager.publicDropView can be skipped, however, parent.removeView is still required. But you need to check it to be sure.

**Review by piaskowyk — CHANGES_REQUESTED** [review]

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java (hunk 1 above)
Comment (Latropos) [reply android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:605]: Yes, when you move the condition to skip only `parent.removeView(view)` the bug does not appear.

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java [hunk 2]
```diff
@@ -600,6 +600,7 @@ private void maybeDropAncestors(View exitingView) {
 
   private void removeView(View view, @Nullable ViewGroup parent) {
     int tag = view.getId();
+
```
Comment (piaskowyk) [inline android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:603]: Let's revert this change

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java [hunk 3]
```diff
@@ -610,7 +611,7 @@ private void removeView(View view, @Nullable ViewGroup parent) {
       mReanimatedNativeHierarchyManager.publicDropView(view);
     }
 
-    if (parent != null) {
+    if (parent != null && tag != -1) {
```
Comment (piaskowyk) [inline android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:614]: If I understand correctly, `view` is a child of `parent`. Could you explain me why we can't remove from his parent?

**Comment by brentlecomte** [comment]
Any update regarding this pr? Running into the crashes described above and hoping this will fix it.

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
[the remark this answers is not in the document]
Comment (piaskowyk) [reply android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:1]: and we need to test it well

**Comment by Latropos** [comment]
@Piaskowy Suggested changes fix #4437, but app still crashes on #4306

<details> <summary>The error log is the same (except for PID etc.)</summary>E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.swmansion.reanimated.example, PID: 7138
    java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)
        at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2099)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4287)
        at android.view.View.draw(View.java:23197)
        at android.view.View.updateDisplayListIfDirty(View.java:22061)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.draw(View.java:23197)
        at android.view.View.updateDisplayListIfDirty(View.java:22061)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
E/AndroidRuntime:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4670)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4381)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3600)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:832)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 </details>

**Review by piaskowyk — APPROVED** [review]

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java [hunk 4]
```diff
@@ -529,6 +529,12 @@ private boolean removeOrAnimateExitRecursive(View view, boolean shouldRemove) {
     }
 
     if (hasAnimatedChildren) {
+      if (tag == -1) {
+        // View tags are used to identify views, but it is hard for no-react views with -1 tag.
+        // We shouldn't to manage the lifetime of no-react components.
```
Comment (tomekzaw) [inline android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:534]:
```suggestion
        // We shouldn't manage lifetime of non-react components.
```

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java [hunk 5]
```diff
@@ -529,6 +529,12 @@ private boolean removeOrAnimateExitRecursive(View view, boolean shouldRemove) {
     }
 
     if (hasAnimatedChildren) {
+      if (tag == -1) {
+        // View tags are used to identify views, but it is hard for no-react views with -1 tag.
```
Comment (tomekzaw) [inline android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:533]: I'm not sure if I understand "it is hard for no-react views with -1 tag" correctly, what exactly do you mean?

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java [hunk 6]
```diff
@@ -503,7 +503,7 @@ private boolean removeOrAnimateExitRecursive(View view, boolean shouldRemove) {
         View child = viewGroup.getChildAt(i);
         if (removeOrAnimateExitRecursive(child, shouldRemove)) {
           hasAnimatedChildren = true;
-        } else if (shouldRemove) {
+        } else if (shouldRemove && child.getId() != -1) {
```
Comment (tomekzaw) [inline android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:506]: Sorry for this basic question but could you please explain in which cases `getId()` returns -1?

Comment (Latropos) [reply android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:506]: This means that the view is native only, and not a react one.

File: android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java (hunk 5 above)
Comment (Latropos) [reply android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:533]: I've accidentally merged this PR without fixing this comment 😱 
I opened this: https://github.com/software-mansion/react-native-reanimated/pull/4634 to fix it
