### PR TITLE
Ensure global objects initialization for web

### LINKED ISSUE #3355: [Web]ReferenceError: _frameTimestamp is not defined
## Description
Get this error when upgrading `react-native-reanimated` to `v2.9.0+` on the web (`v2.8.0` works), it works fine on iOS and Android.

image

### Expected behavior 

Works on the web.

### Actual behavior & steps to reproduce 

web not working when upgrading to `v2.9.0+`.

## Snack or minimal code example 

https://github.com/tamagui/starters/tree/main/next-expo-solito

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.68.2     |
| react-native-reanimated              |    2.9.1     |
| NodeJS                               |     16.15.1    |
| Xcode                                |     13.4.1      |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |     45.0.2    |

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

### PR DESCRIPTION
**Pull request by piaskowyk**
## Description

The PR with tree shaking moved global objects initialization for web to another file and then imported it into the `index` file (`import './reanimated2/js-reanimated/global';`). However, the Webpack can lazy import modules, but we don't have any call to this module, so global objects were never initialized.

Fixes #3355

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,5 +1,13 @@
 // tree-shaken side effects
-import './reanimated2/js-reanimated/global';
+import webGlobalIsInitialized from './reanimated2/js-reanimated/global';
+if (!webGlobalIsInitialized) {
+  /* 
+    `webGlobalIsInitialized` should always be `true`, 
+    but we need to use `webGlobalIsInitialized` somewhere to ensure function execution, 
+    in another way, the bundler can remove unused variables. 
+  */
+  console.error('[Reanimated] Unable to initialize global objects for WEB.');
```
Comment (tomekzaw) [inline src/index.ts:9]:
```suggestion
  console.error('[Reanimated] Unable to initialize global objects for Web.');
```

File: src/reanimated2/js-reanimated/global.ts [hunk 2]
```diff
@@ -1,38 +1,40 @@
...
-      "[Reanimated] You can't use `measure` with Chrome Debugger or with web version"
-    );
-    return {
-      x: 0,
-      y: 0,
-      width: 0,
-      height: 0,
-      pageX: 0,
-      pageY: 0,
+export default (() => {
```
Comment (tomekzaw) [inline src/reanimated2/js-reanimated/global.ts:4]: Can we name this lambda `initializeGlobalsForWeb` and call it as
```ts
export default initializeGlobalsForWeb();
```
? Also, a comment here why we need to do it would be valuable.

**Review by tomekzaw — CHANGES_REQUESTED** [review]

**Review by tomekzaw — APPROVED** [review]

**Comment by jer-sen** [comment]
@piaskowyk it does not solve anything since you did not applied the fix to `index.web.ts` which is the file executed on Web...

**Comment by piaskowyk** [comment]
The `index.web.ts` file was added after this PR, and we rewrite this part and got rid of those changes so this PR is no longer related.

**Comment by jer-sen** [comment]
I'm with react-native-reanimated@2.14.4 (last version for Expo SDK 48) and there is the PR's code in `index.ts` but not in the existing `index.web.ts`...

**Comment by oleg3505** [comment]
Hello I'm also working with react-native-reanimated@2.14.4 (Expo SDK 48) and the error with `_frameTimestamp is not defined` is still here for web

**Comment by piaskowyk** [comment]
Did you try Reanimated3?
