### PR TITLE
Fix `setAndForwardRef`  & `TurboModuleRegistry` imports on web 

### LINKED ISSUE #1364: 'TurboModuleRegistry' is not exported from 'react-native' react-native-web
## Description
I am getting this error:

```
Failed to compile.

./node_modules/react-native-reanimated/src/reanimated2/NativeReanimated.js
Attempted import error: 'TurboModuleRegistry' is not exported from 'react-native'.
```

I upgraded react native to 0.63.3, and used react-native-reanimated version **2.0.0-alpha.7**

I am getting this error for **react-native-web**.

Thanks.

### LINKED ISSUE #1377: web: Can't resolve 'react-native/Libraries/Utilities/setAndForwardRef'
## Description
I installed reanimated v2 to my react-native-web project and received this error.

```
Module not found: Can't resolve 'react-native/Libraries/Utilities/setAndForwardRef' in '/Users/hosseinmohammadi/Documents/GitLab/poolkhord/node_modules/react-native-reanimated/src'
```

## Steps To Reproduce

1.

## Package versions

- React: 17.0.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.7
- NodeJS: 12

### PR DESCRIPTION
**Pull request by hosseinmd**
## Description
1.
	Fixes #1377
	
	issue: Can't resolve 'react-native/Libraries/Utilities/setAndForwardRef'
	
	Reanimated used `setAndForwardRef` of react-native internal function which is not on react-native-web. So that is completely wrong, because react-native in a minor update can remove that.

2.
	Fixes #1364
	
	issue: 'TurboModuleRegistry' is not exported from 'react-native' react-native-web
	
	To take TurboModuleRegistry I used require into a condition which is not running on the web platform.

## Changes

- Added `setAndForwardRef` method to the reanimated. Which is working on both web and native. 

## Checklist

- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by hosseinmd** [comment]
I also fixed this https://github.com/software-mansion/react-native-reanimated/issues/1364

File: src/reanimated2/NativeReanimated.js [hunk 1]
```diff
@@ -1,11 +1,13 @@
-import { TurboModuleRegistry, Platform } from 'react-native';
+import { Platform } from 'react-native';
 import reanimatedJS from './js-reanimated';
 
 const InnerNativeModule =
   Platform.OS === 'web'
     ? false
     : global.__reanimatedModuleProxy ||
-      TurboModuleRegistry.getEnforcing('NativeReanimated');
+      require('react-native').TurboModuleRegistry.getEnforcing(
```
Comment (jfrolich) [inline src/reanimated2/NativeReanimated.js:8]: This still requires the `react-native` package to be in the package.json (not great for web-only projects). Perhaps this can be extracted out in a file with a `.native.js` and a `.web.js`?

**Comment by hosseinmd** [comment]
@jfrolich Thank you, I did it.

**Comment by jfrolich** [comment]
Thanks. I came across this as I was patching the package. Thanks for the PR!

**Review by jakub-gonet — COMMENTED** [review]
LGTM, but CI checks are failing, could you please look into that?

**Comment by hosseinmd** [comment]
is there needed to worry about windows or macOS?

**Comment by hosseinmd** [comment]
> is there needed to worry about windows or macOS?

@jakub-gonet

**Comment by jakub-gonet** [comment]
Probably, but I'm not fond of creating separate js files for each platform. For v1, we have 4 versions of the ReanimatedModule + Compat file.

**Comment by jakub-gonet** [comment]
I added files for Windows and MacOS.

But if I'm not wrong if we create `.js` with the web impl and `.native.js` with the native imports it should work everywhere, right? Jest is picking up the native file, so that's the only problem I see with that approach. I couldn't get it to work, maybe you have some suggestions?

**Comment by hosseinmd** [comment]
> I added files for Windows and MacOS.
> 
> But if I'm not wrong if we create `.js` with the web impl and `.native.js` with the native imports it should work everywhere, right? Jest is picking up the native file, so that's the only problem I see with that approach. I couldn't get it to work, maybe you have some suggestions?

Yes, I think so.

**Comment by jakub-gonet** [comment]
Now CI is failing due to the problem I mentioned in the previous comment - jest tries to load `.native.js` file and fails after the native module is not found.

**Comment by hosseinmd** [comment]
Sorry, I missed that, How would you fix that?

**Comment by jakub-gonet** [comment]
I experimented with it a bit and seems like jest matches by filename. I added `.native.js` symlink and looks like it's working.

**Review by jakub-gonet — APPROVED** [review]
CI push build is failing due to some git checkout problem, PR built.
