### PR TITLE
Fix warning about overwriting style with layout animation

### LINKED ISSUE #5395: LayoutAnimations `entering` and `exiting` not working
### Description

Hey yall,

I tried playing around with LayoutAnimations and I love the idea - they're so simple to implement, amazing work!

https://github.com/software-mansion/react-native-reanimated/assets/15199031/3fac8af4-25c7-4482-9a4d-877fe70c30c0

I did notice that there are a few bugs though.

I created a repro here that showcases those bugs: https://github.com/software-mansion/react-native-reanimated/pull/5394

## 1. Exiting not running

The `exiting` animation is not running in the given example.

## 2. Custom `useAnimatedStyle` not running on first mount

On the first mount, the `useAnimatedStyle` for the second card is not properly applied. I think this is a race condition where the LayoutAnimation takes precedence over the `useAnimatedStyle`.

## 3. Some items not showing

Sometimes the items just don't show up.

## 4. `layout` instead of `useAnimatedStyle` does not work

When using `layout` instead of manually using `useAnimatedStyle` it will not consider properties in the `transform` style.

This is how I animate the slide & rotate to the right now:

```tsx
const rotation = useDerivedValue(() => withSpring(index * 15), [index]);

const animatedStyle = useAnimatedStyle(() => {
  return {
    zIndex: -index,
    backgroundColor: item.color,
    transform: [
      {
        translateX: interpolate(rotation.value, [0, 100], [0, 100]),
      },
      {
        translateY: interpolate(rotation.value, [0, 100], [0, -30]),
      },
      {
        scale: interpolate(rotation.value, [0, 100], [1, 0.7]),
      },
      {
        rotate: `${rotation.value}deg`,
      },
    ],
  };
}, [rotation, index, item]);

return (
  <Animated.View
    entering={Entering}
    exiting={Exiting}
    style={[styles.item, animatedStyle]}
  />
);
```

This is how I want to do it:

```tsx
const style = useMemo(() => {
  return {
    zIndex: -index,
    backgroundColor: item.color,
    transform: [
      {
        translateX: x,
      },
      {
        translateY: y,
      },
      {
        scale: scale,
      },
      {
        rotate: `${rotation}deg`,
      },
    ],
  };
}, [rotation, index, item]);

return (
  <Animated.View
    entering={Entering}
    exiting={Exiting}
    layout={Move} // <-- just a default Layout.springify() animation that should animate the props in transform: [...]
    style={[styles.item, style]}
  />
);
```

Let me know if you need more details!

### Steps to reproduce

https://github.com/software-mansion/react-native-reanimated/pull/5394 <-- open the new page

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/pull/5394

### Reanimated version

3.5.0 (main)

### React Native version

0.72.6

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 15 Pro Simulator

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by Latropos**
## Summary
In this PR https://github.com/software-mansion/react-native-reanimated/pull/4969 I didn't include neither animatedStyles nor styles nested in arrays.
That's why the problem wasn't reported in this example: https://github.com/software-mansion/react-native-reanimated/issues/5395

closes #5395 

|Before|After|
|---|---|
|image|image|

## Test plan

<details><summary>Code</summary>

```jsx
import Animated, {
  useAnimatedStyle,
  SlideInDown,
  ZoomOut,
  useDerivedValue,
  withSpring,
  interpolate,
} from 'react-native-reanimated';
import { StyleSheet, View } from 'react-native';

import React, { useEffect, useState } from 'react';

interface Item {
  color: string;
}

function getRandomColor(): string {
  return '#' + Math.floor(Math.random() * 16777215).toString(16);
}

const Entering = SlideInDown.springify().mass(1).stiffness(1000).damping(500);
const Exiting = ZoomOut.springify().mass(1).stiffness(1000).damping(500);

function ItemComponent({ item, index }: { item: Item; index: number }) {
  const rotation = useDerivedValue(() => withSpring(index * 15), [index]);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      zIndex: -index,
      backgroundColor: item.color,
      transform: [
        {
          translateX: interpolate(rotation.value, [0, 100], [0, 100]),
        },
        {
          translateY: interpolate(rotation.value, [0, 100], [0, -30]),
        },
        {
          scale: interpolate(rotation.value, [0, 100], [1, 0.7]),
        },
        {
          rotate: `${rotation.value}deg`,
        },
      ],
    };
  }, [rotation, index, item]);

  return (
    <Animated.View
      entering={Entering}
      exiting={Exiting}
      style={[styles.item, animatedStyle]}
    />
  );
}

export default function StackedLayoutAnimationExample() {
  const [items, setItems] = useState<Item[]>([
    { color: 'red' },
    { color: 'green' },
  ]);

  useEffect(() => {
    const interval = setInterval(() => {
      setItems((i) => [{ color: getRandomColor() }, ...i]);
    }, 1500);
    return () => clearInterval(interval);
  }, []);

  return (
    <View style={styles.container}>
      {items.map((item, index) => {
        if (index > 2) {
          return null;
        }
        return <ItemComponent key={item.color} item={item} index={index} />;
      })}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  item: {
    width: 100,
    height: 150,
    borderRadius: 15,
    position: 'absolute',
  },
});
```
</details>

### CODE REVIEW

File: src/animationBuilder.tsx [hunk 1]
```diff
@@ -25,12 +26,52 @@ const mockTargetValues: LayoutAnimationsValues = {
   currentBorderRadius: 0,
 };
 
+function maybeReportOverwrittenProperties(
+  layoutAnimationStyle: StyleProps,
+  style: NestedArray<StyleProps>,
+  displayName: string
+) {
+  function getCommonProperties(
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:34]: Does function `getCommonProperties` need to be nested inside `maybeReportOverwrittenProperties`?

File: src/animationBuilder.tsx [hunk 2]
```diff
@@ -25,12 +26,52 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+
+  const commonProperties = getCommonProperties(layoutAnimationStyle, style);
+
+  if (commonProperties.length > 0) {
+    console.warn(
+      `[Reanimated] ${
+        commonProperties.length === 1 ? 'Property' : 'Properties: '
+      } "${commonProperties.join(
+        ', '
+      )}" of ${displayName} may be overwritten with layout animation. Please create a wrapper with the layout animation you want to apply.`
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:64]:
```suggestion
      )}" of ${displayName} may be overwritten by a layout animation. Please wrap your component with an animated view and apply the layout animation on the wrapper.`
```

File: src/animationBuilder.tsx [hunk 3]
```diff
@@ -25,12 +26,52 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+      : [secondStyle];
+    const commonKeys: Array<string> = [];
+
+    secondStyleFlat.forEach((s) => {
+      if ('initial' in s) {
+        s = s.initial.value;
+      }
+
+      const commonStyleKeys = Object.keys(s).filter((key) =>
+        Object.prototype.hasOwnProperty.call(layoutStyle, key)
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:49]: Why not just `key in layoutStyle`?

File: src/animationBuilder.tsx [hunk 4]
```diff
@@ -25,12 +26,52 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+      );
+      commonKeys.push(...commonStyleKeys);
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:51]: Why not just use `commonKeys.concat`?

File: src/animationBuilder.tsx [hunk 5]
```diff
@@ -42,21 +83,13 @@ export function maybeBuild(
...
-        `[Reanimated] ${
-          commonProperties.length === 1 ? 'Property' : 'Properties: '
-        } "${commonProperties.join(
-          ', '
-        )}" of ${displayName} may be overwritten with layout animation. Please create a wrapper with the layout animation you want to apply.`
+    if (__DEV__) {
+      maybeReportOverwrittenProperties(
+        layoutAnimationStyle,
+        style || {},
+        displayName
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:92]: Does it make sense to call `maybeReportOverwrittenProperties` for an empty object if `style` is undefined?
```suggestion
    if (__DEV__ && style) {
      maybeReportOverwrittenProperties(
        layoutAnimationStyle,
        style,
        displayName
```

File: src/animationBuilder.tsx [hunk 6]
```diff
@@ -42,21 +83,13 @@ export function maybeBuild(
...
-    if (commonProperties.length > 0) {
-      console.warn(
-        `[Reanimated] ${
-          commonProperties.length === 1 ? 'Property' : 'Properties: '
-        } "${commonProperties.join(
-          ', '
-        )}" of ${displayName} may be overwritten with layout animation. Please create a wrapper with the layout animation you want to apply.`
+    if (__DEV__) {
+      maybeReportOverwrittenProperties(
+        layoutAnimationStyle,
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:90]: Let's use `layoutAnimation.animations` directly here instead of assigning it to `layoutAnimationStyle`.
```suggestion
        layoutAnimation.animations,
```

File: src/animationBuilder.tsx [hunk 7]
```diff
@@ -25,12 +26,52 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+    });
+    return commonKeys;
+  }
+
+  const commonProperties = getCommonProperties(layoutAnimationStyle, style);
+
+  if (commonProperties.length > 0) {
+    console.warn(
+      `[Reanimated] ${
+        commonProperties.length === 1 ? 'Property' : 'Properties: '
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:61]:
```suggestion
        commonProperties.length === 1 ? 'Property' : 'Properties '
```

File: src/animationBuilder.tsx [hunk 8]
```diff
@@ -25,12 +26,52 @@ const mockTargetValues: LayoutAnimationsValues = {
   currentBorderRadius: 0,
 };
 
+function maybeReportOverwrittenProperties(
+  layoutAnimationStyle: StyleProps,
+  style: NestedArray<StyleProps>,
+  displayName: string
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:32]: Maybe we should rename it to `componentName`?

File: src/animationBuilder.tsx [hunk 9]
```diff
@@ -25,12 +26,52 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+) {
+  function getCommonProperties(
+    layoutStyle: object,
+    secondStyle: object | Array<object>
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:36]: Can we use something more specific than `object` here?

File: src/animationBuilder.tsx [hunk 10]
```diff
@@ -25,12 +26,52 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+  ) {
+    const secondStyleFlat = Array.isArray(secondStyle)
+      ? secondStyle.flat()
+      : [secondStyle];
+    const commonKeys: Array<string> = [];
+
+    secondStyleFlat.forEach((s) => {
+      if ('initial' in s) {
+        s = s.initial.value;
+      }
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:46]: Why do we need this piece of code?

**Review by tomekzaw — CHANGES_REQUESTED** [review]

File: src/animationBuilder.tsx (hunk 1 above)
Comment (Latropos) [reply src/animationBuilder.tsx:34]: No, it doesn't

File: src/animationBuilder.tsx (hunk 4 above)
Comment (Latropos) [reply src/animationBuilder.tsx:51]: Good catch, It seems, that concat should be a little faster: https://www.measurethat.net/Benchmarks/Show/7699/0/array-concat-vs-spread-vs-push-spread-loop-apply#latest_results_block

File: src/animationBuilder.tsx (hunk 8 above)
Comment (Latropos) [reply src/animationBuilder.tsx:32]: We use this string from `createAnimatedComponent`:
```tsx
  AnimatedComponent.displayName = `AnimatedComponent(${
    Component.displayName || Component.name || 'Component'
  })`;
```
So I would keep the current name

File: src/animationBuilder.tsx (hunk 10 above)
Comment (Latropos) [reply src/animationBuilder.tsx:46]: To include animated style, for example here we should throw an error: https://github.com/software-mansion/react-native-reanimated/issues/5395

Comment (tomekzaw) [reply src/animationBuilder.tsx]: Okay, this makes sense, so `'initial' in s` is to check if `s` is an animated style?

If yes, maybe we should add `isAnimatedStyle` function in a separate PR for cases like this one.

File: src/animationBuilder.tsx [hunk 11]
```diff
@@ -25,12 +26,50 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+    : [secondStyle];
+
+  let commonKeys: Array<string> = [];
+  secondStyleFlat.forEach((s) => {
+    if ('initial' in s) {
+      s = s.initial.value; // Include properties of animated style
+    }
+
+    const commonStyleKeys = Object.keys(s).filter((key) => key in layoutStyle);
+    commonKeys = commonKeys.concat(...commonStyleKeys);
```
Comment (tomekzaw) [inline src/animationBuilder.tsx:44]: It should work without `...`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat
```suggestion
    commonKeys = commonKeys.concat(commonStyleKeys);
```

File: src/animationBuilder.tsx (hunk 8 above)
Comment (tomekzaw) [reply src/animationBuilder.tsx:52]: Okay, thanks for the response

**Review by tomekzaw — APPROVED** [review]
Thanks for adding this warning!

File: src/animationBuilder.tsx [hunk 12]
```diff
@@ -25,12 +26,50 @@ const mockTargetValues: LayoutAnimationsValues = {
   currentBorderRadius: 0,
 };
 
+function getCommonProperties(
+  layoutStyle: StyleProps,
+  secondStyle: StyleProps | Array<StyleProps>
```
Comment (tjzel) [inline src/animationBuilder.tsx:31]:
```suggestion
  componentStyle: StyleProps | Array<StyleProps>
```

File: src/animationBuilder.tsx [hunk 13]
```diff
@@ -25,12 +26,50 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+) {
+  const secondStyleFlat = Array.isArray(secondStyle)
```
Comment (tjzel) [inline src/animationBuilder.tsx:33]:
```suggestion
  const stylesFlatArray = Array.isArray(secondStyle)
```

File: src/animationBuilder.tsx [hunk 14]
```diff
@@ -25,12 +26,50 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+    ? secondStyle.flat()
+    : [secondStyle];
+
+  let commonKeys: Array<string> = [];
+  secondStyleFlat.forEach((s) => {
```
Comment (tjzel) [inline src/animationBuilder.tsx:38]:
```suggestion
  secondStyleFlat.forEach((style) => {
```

File: src/animationBuilder.tsx [hunk 15]
```diff
@@ -25,12 +26,50 @@ const mockTargetValues: LayoutAnimationsValues = {
...
+    if ('initial' in s) {
+      s = s.initial.value; // Include properties of animated style
+    }
+
+    const commonStyleKeys = Object.keys(s).filter((key) => key in layoutStyle);
+    commonKeys = commonKeys.concat(commonStyleKeys);
+  });
+  return commonKeys;
```
Comment (tjzel) [inline src/animationBuilder.tsx:46]: You might get duplicate keys that way. How about:

```ts
function getCommonProperties(
  layoutStyle: StyleProps,
  secondStyle: StyleProps | Array<StyleProps>
) {
  let stylesFlatArray = Array.isArray(secondStyle)
    ? secondStyle.flat()
    : [secondStyle];

  stylesFlatArray = stylesFlatArray.map((style) => {
    if ('initial' in style) {
      return style.initial.value;
    }
    return style;
  });

  const componentStylesKeys = stylesFlatArray.flatMap((style) =>
    Object.keys(style)
  );

  const commonKeys = Object.keys(layoutStyle).filter((key) =>
    componentStylesKeys.includes(key)
  );

  return commonKeys;
}
```

**Review by tjzel — APPROVED** [review]
All looks good, names of some variables could be better but it's very minor. Left a suggestion if you are interested in it, but your solution is good as well.

TS types are not the best, but since this file hasn't undergone proper typing it's okay.
