### PR TITLE
Fix handling UTF-8 object keys

### LINKED ISSUE #6220: ShareableObject unable to handle utf-8 key on Android
### Description

```
 for (size_t i = 0, size = data_.size(); i < size; i++) {
    obj.setProperty(
        rt, data_[i].first.c_str(), data_[i].second->getJSValue(rt));
  }

```

`data_[i].first.c_str()` can't handle utf-8.

the following code works:

```
  for (size_t i = 0, size = data_.size(); i < size; i++) {
      std::cout << "shareable" << data_[i].first.c_str() << std::endl;
      obj.setProperty(
        rt, jsi::PropNameID::forUtf8(rt, data_[i].first.c_str()), data_[i].second->getJSValue(rt));
  }
```

### Steps to reproduce

when save the following data in SharedValue
```
{
"中文": 0,
"键值", 1,
}
```

I got something like the following when read:
```
{"ç®è¤ç§":0,"å¿ç§":0}
```

### Snack or a link to a repository

https://snack.expo.dev/NAmgJOBZPjyaxE2nLFZRf

### Reanimated version

3.12.1

### React Native version

0.74.84

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by coado**
## Summary

Regarding this [issue](https://github.com/software-mansion/react-native-reanimated/issues/6220) the PR solves it by creating a jsi key string from utf8.

Fixes #6220.

## Test plan

Tested on demo provided in issue mentioned above.

### CODE REVIEW

File: packages/react-native-reanimated/Common/cpp/worklets/SharedItems/Shareables.cpp [hunk 1]
```diff
@@ -233,7 +233,7 @@ ShareableObject::ShareableObject(
 jsi::Value ShareableObject::toJSValue(jsi::Runtime &rt) {
   auto obj = jsi::Object(rt);
   for (size_t i = 0, size = data_.size(); i < size; i++) {
-    obj.setProperty(rt, data_[i].first.c_str(), data_[i].second->toJSValue(rt));
+      obj.setProperty(rt, jsi::String::createFromUtf8(rt, data_[i].first), data_[i].second->toJSValue(rt));
```
Comment (tomekzaw) [inline packages/react-native-reanimated/Common/cpp/worklets/SharedItems/Shareables.cpp:236]: Let's restore the original indentation.
```suggestion
    obj.setProperty(rt, jsi::String::createFromUtf8(rt, data_[i].first), data_[i].second->toJSValue(rt));
```

Comment (coado) [reply packages/react-native-reanimated/Common/cpp/worklets/SharedItems/Shareables.cpp:236]: Oh right! Too much prettier for me 😅

**Review by tomekzaw — APPROVED** [review]
