### PR TITLE
Update type exports to fix build warnings

### LINKED ISSUE #5073: Type build warnings in reanimated 3.5.1
### Description

When running our app with reanimated 3.5.1 there are a ton of build warnings about missing or invalid exports. This has to do with a recent change https://github.com/software-mansion/react-native-reanimated/pull/4844 that attempted to fix exposure of some methods to the public api, but by explicitly exporting types as regular exports it causes a bunch of build warnings. I have only tested on web but I am assuming the same will happen on mobile builds. Here is a short snippet of some of the warnings and a screenshot

```
WARNING in ./node_modules/react-native-reanimated/lib/module/reanimated2/index.web.ts:211
export 'StyleProps' (reexported as 'StyleProps') was not found in './commonTypes' (possible exports: IOSReferenceFrame, InterfaceOrientation, KeyboardState, ReduceMotion, SensorType)
  209 | } from './layoutReanimation';
  210 | export { getRelativeCoords, ComponentCoords, isSharedValue } from './utils';
> 211 | export {
  212 |   StyleProps,
  213 |   SharedValue,
  214 |   AnimatableValueObject,

WARNING in ./node_modules/react-native-reanimated/lib/module/reanimated2/index.web.ts:211
export 'ValueRotation' (reexported as 'ValueRotation') was not found in './commonTypes' (possible exports: IOSReferenceFrame, InterfaceOrientation, KeyboardState, ReduceMotion, SensorType)
  209 | } from './layoutReanimation';
  210 | export { getRelativeCoords, ComponentCoords, isSharedValue } from './utils';
> 211 | export {
  212 |   StyleProps,
  213 |   SharedValue,
  214 |   AnimatableValueObject,

WARNING in ./node_modules/react-native-reanimated/lib/module/reanimated2/index.web.ts:211
export 'Value3D' (reexported as 'Value3D') was not found in './commonTypes' (possible exports: IOSReferenceFrame, InterfaceOrientation, KeyboardState, ReduceMotion, SensorType)
  209 | } from './layoutReanimation';
  210 | export { getRelativeCoords, ComponentCoords, isSharedValue } from './utils';
> 211 | export {
  212 |   StyleProps,
  213 |   SharedValue,
  214 |   AnimatableValueObject,

```

Screenshot 2023-09-12 at 4 27 23 PM

### Steps to reproduce

1. Checkout a clean version of the project
2. Install packages and run build
3. In `WebExample/` run yarn start
4. You will see about 52 warnings about export errors

### Snack or a link to a repository

Reproducible by running the Web Example

### Reanimated version

3.5.1

### React Native version

0.72.3

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by khevamann**
## Summary

This PR addresses an issue where building for web produces a ton of warnings about missing imports. closes #5073 

## Test plan

N/A

### CODE REVIEW

File: src/reanimated2/index.ts [hunk 1]
```diff
@@ -208,37 +211,34 @@ export {
...
 export { FrameInfo } from './frameCallback';
 export { getUseOfValueInStyleWarning } from './pluginUtils';
-export {
-  withReanimatedTimer,
-  advanceAnimationByTime,
-  advanceAnimationByFrame,
-  setUpTests,
-  getAnimatedStyle,
-} from './jestUtils';
+export * from './jestUtils';
```
Comment (khevamann) [inline src/reanimated2/index.ts:241]: jestUtils is unused on web and has a mock, so by directly exporting these methods the build was throwing warnings. I checked and these are the exact exports of jestUtils so it is safe to export all. If this is an issue then we would need to create a copy of this file as a web override that can have no exports from jestUtils.

**Comment by tjzel** [comment]
Thanks for this PR! I made some changes so we would not encounter this problem in the future (I hope).

**Review by tjzel — APPROVED** [review]
