### PR TITLE
fix: `useAnimatedProps` on input component not working on web 

### LINKED ISSUE #6202: useAnimatedProps not updating on web
### Description

when i go to here :

https://docs.swmansion.com/react-native-reanimated/examples/slider

the TextInput updates as you slide the slider

when i run the snack web client the TextInput does not update

[same issue when i run the code locally in my workspace on the web]

### Steps to reproduce

go to this snack and run on web, the TextInput does not update : 

~~https://snack.expo.io/?platform=android&name=Slider%20%7C%20React%20Native%20Reanimated&dependencies=react-native-reanimated%40*%2Creact-native-gesture-handler%40*%2C%40shopify%2Fflash-list%40*&hideQueryParams=true&sourceUrl=https%3A%2F%2Fdocs.swmansion.com%2Freact-native-reanimated%2Fexamples%2FSlider.js~~

(better snack version:)

https://snack.expo.dev/@oxbits/slider-%7C-react-native-reanimated

### Snack or a link to a repository

~~https://snack.expo.io/?platform=android&name=Slider%20%7C%20React%20Native%20Reanimated&dependencies=react-native-reanimated%40*%2Creact-native-gesture-handler%40*%2C%40shopify%2Fflash-list%40*&hideQueryParams=true&sourceUrl=https%3A%2F%2Fdocs.swmansion.com%2Freact-native-reanimated%2Fexamples%2FSlider.js~~

(better snack version:)

https://snack.expo.dev/@oxbits/slider-%7C-react-native-reanimated

### Reanimated version

3.10.1 or 3.12.1 [i tried both and others too]

### React Native version

0.74

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

all of this makes me wonder why it works on the documentation web page but not in the snack or on my local box ?

### PR DESCRIPTION
**Pull request by patrycjakalinska**
## Summary

Fixes #6202.
Due to React Native's `_valueTracker`, using `useAnimatedProps` won't work on input component. Before when using `react-native-web` <= 18 we were able to set `text` props using `setNativeProps` legacy function. Currently on newer `react-native-web`, (and due to the `_valueTracker`), we were trying to `setAttribute` `text` on input component -unsuccessfully. 
This PR implements fix that checks whether current component is `input` with a prop `text`, if so it updates props directly on it.

With a support from this [PR](https://github.com/software-mansion/react-native-reanimated/pull/6691).

## Test plan

Run **JS props** or **Amount** in `web-example`

### CODE REVIEW

File: packages/react-native-reanimated/src/ReanimatedModule/js-reanimated/index.ts [hunk 1]
```diff
@@ -159,7 +159,17 @@ const updatePropsDOM = (
 
   for (const key in domStyle) {
     if (isAnimatedProps) {
-      (component as HTMLElement).setAttribute(key, domStyle[key]);
+      // We need to explicitly set the 'text' property on input component because React Native's
+      // internal _valueTracker (https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/client/inputValueTracking.js)
+      // prevents updates when only modifying attributes.
+      if (
+        (component as HTMLElement).nodeName.toLowerCase() === 'input' &&
```
Comment (tomekzaw) [inline packages/react-native-reanimated/src/ReanimatedModule/js-reanimated/index.ts:166]: nit: `nodeName` always contains the uppercase tag name of an HTML element
```suggestion
        (component as HTMLElement).nodeName === 'INPUT' &&
```

**Review by tomekzaw — APPROVED** [review]
Thanks for the PR! LGTM, but let's wait for @piaskowyk's approval prior to merging.

**Review by piaskowyk — APPROVED** [review]
