### PR TITLE
[Android] Fix commits during drawing

### LINKED ISSUE #8422: Crashes with the error: java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference in method 'void android.view.ViewGroup.dispatchGetDisplayList()'
### Description

I customized a Modal component using the Animated.View component with entering and exiting props. When the Modal closes and navigates to another screen, the app crashes with the error: java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference in method 'void android.view.ViewGroup.dispatchGetDisplayList()'.
I tried removing the exiting prop, and the crash didn't happen.
Not all devices crash—most crashes are related to Oppo/Realme, etc.

### Steps to reproduce

1. create a project with expo (npx create-expo-app@latest)
2. reset project (npm run reset-project)
3. install dependency (npx expo install ahooks react-native-get-random-values uuid react-native-keyboard-controller react-native-paper)
4. prebuild (expo prebuild)
5. add two screen (index and test)
6. add Modal component
7. add a button to open a drawer on index screen
8. navigate to test screen on Modal callback "onConfirm"
9. build a release app and install to a device (oppo or realme)
10. open the app in default index screen, click the button to open the drawer and then click the action
11. the screen change to test screen and then the app crash

### Snack or a link to a repository

https://github.com/rpyoyo/crash-reproduction-react-native-reanimated.git

### Reanimated version

4.1.3

### Worklets version

0.6.1

### React Native version

0.81.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

New Architecture (Fabric renderer)

### Build type

Release app & production bundle

### Device

Real device

### Host machine

Windows

### Device model

Realme GT Neo (RMX3350) Android 13

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by bartlomiejbloniarz**
## Summary

This PR intends to solve the most annoying crash that we currently face on Android. The crash is caused by Reanimated calling `ShadowTree::commit` when handling events that were emitted while in the Android drawing pass.

Performing a commit can cause other changes queued by React Native to also get applied. This can lead to the view hierarchy being modified, which is not allowed while in the draw pass.

To fix this, we have a workaround where if we are in the draw pass, we instead only apply non-layout changes (that can be applied without a ShadowTree commit), and schedule the layout changes to happen when we are outside of the draw call. We want to apply the non-layout updates there to maintain things like transform driven sticky headers.

closes #8422 🤞 

## Test plan

I added a new Android Draw Pass example, it would also make sense to test the sticky header and other event related examples

### CODE REVIEW

File: packages/react-native-reanimated/Common/cpp/reanimated/Fabric/updates/UpdatesRegistry.cpp [hunk 1]
```diff
@@ -38,6 +38,11 @@ void UpdatesRegistry::flushUpdates(UpdatesBatch &updatesBatch) {
   }
 }
 
+UpdatesBatch UpdatesRegistry::getPendingUpdates() const {
+  std::lock_guard<std::mutex> lock{mutex_};
+  return updatesBatch_;
```
[the remark this answers is not in the document]
Comment (bartlomiejbloniarz) [reply packages/react-native-reanimated/Common/cpp/reanimated/Fabric/updates/UpdatesRegistry.cpp]: This is fine, we can't really access it by reference because of the mutex, so it's safer to copy

File: packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java [hunk 2]
```diff
@@ -114,11 +118,32 @@ private void stopUpdatingOnAnimationFrame() {
...
+      startUpdatingOnAnimationFrame();
+      return;
     }
+
+    performOperations();
+  }
+
+  boolean isInDrawPass() {
+    return mDrawPassDetector.isInDrawPass();
   }
```
[the remark this answers is not in the document]
Comment (bartlomiejbloniarz) [reply packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:148]: The both call-sites for this include a main thread assertion, let's not overdo it

File: packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp [hunk 3]
```diff
@@ -127,8 +127,12 @@ bool NativeProxy::isAnyHandlerWaitingForEvent(const std::string &eventName, cons
   return reanimatedModuleProxy_->isAnyHandlerWaitingForEvent(eventName, emitterReactTag);
 }
 
-void NativeProxy::performOperations(const bool isTriggeredByEvent) {
-  reanimatedModuleProxy_->performOperations(isTriggeredByEvent);
+void NativeProxy::performOperations() {
+  reanimatedModuleProxy_->performOperations();
+}
```
Comment (tjzel) [inline packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp:132]: Are these only layout operations? If yes, maybe let's make it `performLayoutOperations` for less ambiguity.

File: packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/DrawPassDetector.java [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+  private final Handler mHandler = new Handler(Looper.getMainLooper());
+  private final Runnable mClearRunnable = () -> mIsInDrawPass = false;
+  private boolean mIsInDrawPass = false;
+  @Nullable private View mDecorView = null;
+
+  private final ViewTreeObserver.OnDrawListener mOnDrawListener =
+      () -> {
+        mIsInDrawPass = true;
+        mHandler.postAtFrontOfQueue(mClearRunnable);
+      };
```
Comment (tjzel) [inline packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/DrawPassDetector.java:24]: Is it possible that next drawing will be put ahead of our callback in the queue, resulting in `mClearRunnable` triggering in the wrong moment?

File: packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp [hunk 5]
```diff
@@ -601,7 +627,7 @@ bool ReanimatedModuleProxy::handleRawEvent(const RawEvent &rawEvent, double curr
   // (res == true), but for now handleEvent always returns false. Thankfully,
   // performOperations does not trigger a lot of code if there is nothing to
   // be done so this is fine for now.
```
Comment (tjzel) [inline packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp:631]: Is this comment still relevant?

File: packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp [hunk 6]
```diff
@@ -55,26 +55,52 @@ constexpr bool shouldUseSynchronousUpdatesInPerformOperations() {
...
-        break;
+    if (allowPartialViews) {
+      folly::dynamic synchronousProps = folly::dynamic::object();
+      folly::dynamic shadowTreeProps = folly::dynamic::object();
+
+      for (const auto &[key, value] : props.items()) {
+        const auto keyStr = key.asString();
+        const bool isColorProp = keyStr == "color" || keyStr.find("Color") != std::string::npos;
+        const bool shouldApplySynchronously =
+            synchronousPropNames.contains(keyStr) && (!shouldRequireIntegerColors || !isColorProp || value.isInt());
```
Comment (tjzel) [inline packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp]:
```suggestion
        const bool isSynchronous =
            synchronousPropNames.contains(keyStr) && (!shouldRequireIntegerColors || !isColorProp || value.isInt());
```

File: packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp [hunk 7]
```diff
@@ -55,26 +55,52 @@ constexpr bool shouldUseSynchronousUpdatesInPerformOperations() {
...
+        shadowTreeUpdatesBatch.emplace_back(shadowNode, std::move(shadowTreeProps));
+      }
     } else {
-      shadowTreeUpdatesBatch.emplace_back(shadowNode, props);
+      bool hasOnlySynchronousProps = true;
+
+      for (const auto &[key, value] : props.items()) {
+        const auto keyStr = key.asString();
+        const bool isColorProp = keyStr == "color" || keyStr.find("Color") != std::string::npos;
+        if (!synchronousPropNames.contains(keyStr) || (shouldRequireIntegerColors && isColorProp && !value.isInt())) {
```
Comment (tjzel) [inline packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp]:
```suggestion
 const bool isSynchronous =
            synchronousPropNames.contains(keyStr) && (!shouldRequireIntegerColors || !isColorProp || value.isInt());
        if (!isSynchronous) {
```

**Review by tjzel — APPROVED** [review]
I left some questions and minor suggestions, but all looks good to me 👍

File: packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp (hunk 3 above)
Comment (bartlomiejbloniarz) [reply packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp:132]: These are both, and usually we go through this path. Only on android we go through performNonLayoutOps, and only when handling a synchronous event in the draw pass. This is basically to have animations like sticky header that is driven by transforms to work.

File: packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/DrawPassDetector.java (hunk 4 above)
Comment (bartlomiejbloniarz) [reply packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/DrawPassDetector.java:24]: If it is put ahead then we probably shouldn't clear as it is still a draw pass? I guess a bigger problem would be if something that is not a draw pass was put before the clear, but in that case we will just skip layout-prop animation for the time being and apply it later. I think that's better than the crashes we experience now.

File: packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp (hunk 5 above)
Comment (bartlomiejbloniarz) [reply packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp:631]: Yes it is as the logic is still the same on iOS. Though you sent me on a little tangent, because I got worried that this performOperations call might still happen during the draw pass, but [handleRawEvent is not called on Android](https://github.com/software-mansion/react-native-reanimated/blob/26326bd145d0d5a5e473fc0120db5096d475dd48/packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp#L52) so we avoid this path.

obraz

This is what it looks like (the second `performNonLayoutOperations` call is basically empty since we drained the updates before)

**Comment by huextrat** [comment]
Will this fix https://github.com/software-mansion/react-native-reanimated/issues/8907 also?

**Comment by bartlomiejbloniarz** [comment]
It's the same error, they just added better logging in Android 16
