### PR TITLE
[Android] Cleanup animated sensors in NativeProxy destructor

### LINKED ISSUE #3645: [Android] - useAnimatedSensor on reload - JNI DETECTED ERROR IN APPLICATION: java_object == null
### Description

When using the useAnimatedSensor hook, the native vm will crash whenever the javascript VM is reloaded (when using development reload, or when using Codepush (it reloads the VM when applying a codepush). 

[Easily reproduce-able with this snack](https://snack.expo.dev/@pretzel11/reanimated-sensor-crash)

### Steps to reproduce

1. Load snack on Android
2. Observe the animation functioning correctly when tilting the device.
3. shake the device to bring up the dev menu
4. select "reload"
5. observe the crash.

[reanimCrash.log](https://github.com/software-mansion/react-native-reanimated/files/9711568/reanimCrash.log)

```

09-22 11:27:50.307 com.squareup.cash.developer(22934) 26610 F .cash.develope:  java_vm_ext.cc:594] JNI DETECTED ERROR IN APPLICATION: java_object == null
09-22 11:27:50.307 com.squareup.cash.developer(22934) 26610 F .cash.develope:  java_vm_ext.cc:594]     in call to GetObjectClass
09-22 11:27:50.307 com.squareup.cash.developer(22934) 26610 F .cash.develope:  java_vm_ext.cc:594]     from void com.facebook.react.bridge.queue.NativeRunnable.run()
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675] Runtime aborting...
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675] Dumping all threads without mutator lock held
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675] All threads:
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675] DALVIK THREADS (53):
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675] "mqt_js" prio=5 tid=17 Runnable
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x13647548 self=0xb4000070fbe9d400
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | sysTid=26610 nice=0 cgrp=top-app sched=0/0 handle=0x71062e1cb0
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | state=R schedstat=( 2149856140 597609090 5968 ) utm=175 stm=39 core=7 HZ=100
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | stack=0x71061de000-0x71061e0000 stackSize=1039KB
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | held mutexes= "abort lock" "mutator lock"(shared held)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #00 pc 00000000005376cc  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+128) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #01 pc 00000000006f0e24  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+236) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #02 pc 00000000006fe6b0  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+208) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #03 pc 0000000000364174  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+440) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #04 pc 00000000006fce50  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+280) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #05 pc 00000000006d7ec4  /apex/com.android.art/lib64/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+212) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #06 pc 00000000006d2b24  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1016) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #07 pc 0000000000016ea8  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+80) (BuildId: b77c57f68a484ed93d5a7eda59d83bf9)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #08 pc 0000000000016450  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352) (BuildId: b77c57f68a484ed93d5a7eda59d83bf9)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #09 pc 0000000000445224  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1612) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #10 pc 000000000032feb4  /apex/com.android.art/lib64/libart.so (art::JNI<false>::GetObjectClass(_JNIEnv*, _jobject*)+996) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #11 pc 000000000006c980  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libreanimated.so (reanimated::NativeProxy::unregisterSensor(int)+40) (BuildId: e582d26d0d664d4e4e870be9920fb145bb65446c)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #12 pc 00000000000388e0  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libreanimated.so (reanimated::AnimatedSensorModule::~AnimatedSensorModule()+56) (BuildId: e582d26d0d664d4e4e870be9920fb145bb65446c)
09-22 11:27:50.488 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #13 pc 00000000000418e0  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libreanimated.so (reanimated::NativeReanimatedModule::~NativeReanimatedModule()+184) (BuildId: e582d26d0d664d4e4e870be9920fb145bb65446c)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #14 pc 000000000001cc40  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes-executor-release.so (facebook::jsi::DecoratedHostObject::~DecoratedHostObject()+76) (BuildId: 513960a12845eb691b2683c14168b8c28bf6ae70)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #15 pc 000000000007033c  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #16 pc 00000000000798fc  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #17 pc 0000000000134d58  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #18 pc 00000000000cc884  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #19 pc 00000000000d1ce0  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #20 pc 00000000000d1ca4  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #21 pc 000000000007033c  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #22 pc 00000000000745d4  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #23 pc 0000000000074608  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes.so (???) (BuildId: 5d5c402fd4b45a27fb3d4a2c73dac455227fbe05)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #24 pc 000000000001b7a0  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes-executor-release.so (???) (BuildId: 513960a12845eb691b2683c14168b8c28bf6ae70)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #25 pc 000000000001b414  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes-executor-release.so (facebook::react::JSIExecutor::~JSIExecutor()+476) (BuildId: 513960a12845eb691b2683c14168b8c28bf6ae70)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #26 pc 000000000001b600  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libhermes-executor-release.so (facebook::react::HermesExecutor::~HermesExecutor()+80) (BuildId: 513960a12845eb691b2683c14168b8c28bf6ae70)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #27 pc 0000000000069c9c  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libreactnativejni.so (???) (BuildId: 7656384588be6ec394582109bb0c75aa4cf6bac7)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #28 pc 00000000000688ac  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libreactnativejni.so (???) (BuildId: 7656384588be6ec394582109bb0c75aa4cf6bac7)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #29 pc 000000000005b648  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libreactnativejni.so (facebook::jni::detail::MethodWrapper<void (facebook::react::JNativeRunnable::*)(), &(facebook::react::JNativeRunnable::run()), facebook::react::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::react::JNativeRunnable, facebook::react::Runnable>::JavaPart, facebook::react::Runnable, void>::_javaobject*>)+32) (BuildId: 7656384588be6ec394582109bb0c75aa4cf6bac7)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #30 pc 000000000005b5c0  /data/app/~~vN4QJiCVw0YFbOWd91upTw==/com.squareup.cash.developer-3h7-5SL8vyN0IJalGNsMVw==/lib/arm64/libreactnativejni.so (facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::react::JNativeRunnable, facebook::react::Runnable>::JavaPart, facebook::react::Runnable, void>::_javaobject*>), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::react::JNativeRunnable, facebook::react::Runnable>::JavaPart, facebook::react::Runnable, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*, void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::react::JNativeRunnable, facebook::react::Runnable>::JavaPart, facebook::react::Runnable, void>::_javaobject*>))+60) (BuildId: 7656384588be6ec394582109bb0c75aa4cf6bac7)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at com.facebook.react.bridge.queue.NativeRunnable.run(Native method)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.os.Handler.handleCallback(Handler.java:938)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.os.Handler.dispatchMessage(Handler.java:99)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.os.Looper.loopOnce(Looper.java:233)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.os.Looper.loop(Looper.java:344)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at java.lang.Thread.run(Thread.java:1012)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675] 
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675] "main" prio=7 tid=1 Native
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x73482a48 self=0xb400007123012400
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | sysTid=22934 nice=-4 cgrp=top-app sched=0/0 handle=0x71c1ca4500
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | state=S schedstat=( 21151770863 234090100 11584 ) utm=1387 stm=728 core=6 HZ=100
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | stack=0x7fd860d000-0x7fd860f000 stackSize=8188KB
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   | held mutexes=
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #00 pc 0000000000075f30  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32) (BuildId: bbbdeb7c87c74f1491f92c6e605095b0)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #01 pc 000000000047cc80  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+140) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #02 pc 000000000075b88c  /apex/com.android.art/lib64/libart.so (artJniMethodEnd+204) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   native: #03 pc 000000000020facc  /apex/com.android.art/lib64/libart.so (art_jni_method_end+12) (BuildId: 56e704c544e6c624201be2ab4933e853)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at com.swmansion.reanimated.NativeProxy$SensorSetter.sensorSetter(Native method)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at com.swmansion.reanimated.sensor.ReanimatedSensorListener.onSensorChanged(ReanimatedSensorListener.java:46)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:964)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:908)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.os.MessageQueue.nativePollOnce(Native method)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.os.MessageQueue.next(MessageQueue.java:339)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.os.Looper.loopOnce(Looper.java:179)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.os.Looper.loop(Looper.java:344)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at android.app.ActivityThread.main(ActivityThread.java:8212)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at java.lang.reflect.Method.invoke(Native method)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-22 11:27:50.489 com.squareup.cash.developer(22934) 26610 F .cash.develope:  runtime.cc:675]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### Snack or a link to a repository

https://snack.expo.dev/@pretzel11/reanimated-sensor-crash

### Reanimated version

2.10.0

### React Native version

0.69.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

OnePlus Pro 9

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by jwajgelt**
## Summary
Fixes #3645

The reason for the crash when reloading was that, when the sensor listeners where cleaned up in the `AnimatedSensorModule`'s destructor, the `NativeProxy` object used for calling JNI functions has already been destroyed, causing a null pointer dereference.

This PR moves the sensor listener cleanup to `NativeProxy`'s destructor, where JNI functions are still safe to call.

## Test plan
In the Example app:
- go to the "Use Animated Sensor" example
- trigger a reload (e.g. by typing "r" in metro)
- 🤞 for no crash

### CODE REVIEW

File: android/src/main/cpp/NativeProxy.cpp [hunk 1]
```diff
@@ -63,6 +63,11 @@ NativeProxy::NativeProxy(
 NativeProxy::~NativeProxy() {
   // removed temporary, new event listener mechanism need fix on the RN side
   // reactScheduler_->removeEventListener(eventListener_);
+
+  // cleanup all animated sensors here, since NativeProxy
+  // has already been destroyed when AnimatedSensorModule's
+  // destructor is ran
+  _nativeReanimatedModule->cleanupSensors();
```
Comment (piaskowyk) [inline android/src/main/cpp/NativeProxy.cpp:70]: Is it only an Android-specific problem? Maybe the destructor of Reanimated module would be a better place for it.

Comment (jwajgelt) [reply android/src/main/cpp/NativeProxy.cpp:70]: It is, it's related to the `NativeProxy` JNI hybrid object being destroyed before the `AnimatedSensorModule`, which doesn't seem to happen with the iOS analogues.

**Comment by DenianFossatti** [comment]
Hi, sorry if this is not the right place for this, but you guys are planning to release a 2.x.x version for this fix ? @jwajgelt 

I'm currently facing a issue similar to #2710 and #3645. When we reload the app after a codepush update, sometimes the app crashes and after making a patch using patch-package with almost all the changes that this PR contains, the app seems to not crash anymore.

One more thing, can you guys validate if this patch can break something on 2.14.4 ?

`diff --git a/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp b/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp
index 83948c9..d6450f5 100644
--- a/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp
+++ b/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp
@@ -16,11 +16,7 @@ AnimatedSensorModule::AnimatedSensorModule(
       runtimeManager_(runtimeManager) {}
 
 AnimatedSensorModule::~AnimatedSensorModule() {
-  // It is called during app reload because app reload doesn't call hooks
-  // unmounting
-  for (auto sensorId : sensorsIds_) {
-    platformUnregisterSensorFunction_(sensorId);
-  }
+  assert(sensorsIds_.empty());
 }
 
 jsi::Value AnimatedSensorModule::registerSensor(
@@ -72,4 +68,11 @@ void AnimatedSensorModule::unregisterSensor(const jsi::Value &sensorId) {
   platformUnregisterSensorFunction_(sensorId.asNumber());
 }
 
+void AnimatedSensorModule::unregisterAllSensors() {
+  for (auto sensorId : sensorsIds_) {
+    platformUnregisterSensorFunction_(sensorId);
+  }
+  sensorsIds_.clear();
+}
+
 } // namespace reanimated
diff --git a/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.h b/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.h
index 76b652b..cffef9b 100644
--- a/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.h
+++ b/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.h
@@ -36,6 +36,7 @@ class AnimatedSensorModule {
       const jsi::Value &interval,
       const jsi::Value &sensorDataContainer);
   void unregisterSensor(const jsi::Value &sensorId);
+  void unregisterAllSensors();
 };
 
 } // namespace reanimated
diff --git a/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp b/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp
index 85cbe9c..6d9d686 100644
--- a/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp
+++ b/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp
@@ -368,4 +368,8 @@ void NativeReanimatedModule::unsubscribeFromKeyboardEvents(
   unsubscribeFromKeyboardEventsFunction(listenerId.asNumber());
 }
 
+void NativeReanimatedModule::cleanupSensors() {
+  animatedSensorModule.unregisterAllSensors();
+}
+
 } // namespace reanimated
diff --git a/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.h b/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.h
index ec06185..2740bf5 100644
--- a/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.h
+++ b/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.h
@@ -90,6 +90,9 @@ class NativeReanimatedModule : public NativeReanimatedModuleSpec,
       const jsi::Value &interval,
       const jsi::Value &sensorDataContainer) override;
   void unregisterSensor(jsi::Runtime &rt, const jsi::Value &sensorId) override;
+
+  void cleanupSensors();
+
   jsi::Value subscribeForKeyboardEvents(
       jsi::Runtime &rt,
       const jsi::Value &keyboardEventContainer) override;
diff --git a/node_modules/react-native-reanimated/android/src/main/cpp/NativeProxy.cpp b/node_modules/react-native-reanimated/android/src/main/cpp/NativeProxy.cpp
index fff5022..9080cbe 100644
--- a/node_modules/react-native-reanimated/android/src/main/cpp/NativeProxy.cpp
+++ b/node_modules/react-native-reanimated/android/src/main/cpp/NativeProxy.cpp
@@ -47,6 +47,11 @@ NativeProxy::NativeProxy(
 NativeProxy::~NativeProxy() {
   // removed temporary, new event listener mechanism need fix on the RN side
   // reactScheduler_->removeEventListener(eventListener_);
+
+  // cleanup all animated sensors here, since NativeProxy
+  // has already been destroyed when AnimatedSensorModule's
+  // destructor is ran
+  _nativeReanimatedModule->cleanupSensors();
 }
 
 jni::local_ref<NativeProxy::jhybriddata> NativeProxy::initHybrid(
`

I didn't find where to put this lines of code:

`volatile bool uiRuntimeDestroyed = false;`

and this part, the function doesn't seems to have the same signature, so I didn't make the change

`  int sensorId = platformRegisterSensorFunction_(
      sensorType,
      interval.asNumber(),
      [uiRuntime, sensorType, shareableHandler](double newValues[]) {`

File: Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp [hunk 2]
```diff
@@ -33,7 +29,9 @@ jsi::Value AnimatedSensorModule::registerSensor(
   auto uiRuntime = runtimeHelper->uiRuntime();
 
   int sensorId = platformRegisterSensorFunction_(
-      sensorType, interval.asNumber(), [=](double newValues[]) {
+      sensorType,
+      interval.asNumber(),
+      [uiRuntime, sensorType, shareableHandler](double newValues[]) {
         jsi::Runtime &rt = *uiRuntime;
```
Comment (tomekzaw) [inline Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp:35]: Is it really safe to access `uiRuntime` here?

If not, we can capture `runtimeHelper` (which is a shared pointer) to the lambda and call `runtimeHelper->uiRuntime();` inside (like we do in many other places).

File: Common/cpp/NativeModules/NativeReanimatedModule.cpp [hunk 3]
```diff
@@ -447,6 +447,10 @@ void NativeReanimatedModule::unregisterSensor(
   animatedSensorModule.unregisterSensor(sensorId);
 }
 
+void NativeReanimatedModule::cleanupSensors() {
+  animatedSensorModule.unregisterAllSensors();
+}
```
Comment (tomekzaw) [inline Common/cpp/NativeModules/NativeReanimatedModule.cpp:452]: Can we rename `cleanupSensors` to `unregisterAllSensors` for the sake of consistency?

File: Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp (hunk 2 above)
Comment (jwajgelt) [reply Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp:35]: I think this is outside the scope of this PR, but I might as well. 👍

File: Common/cpp/NativeModules/NativeReanimatedModule.cpp (hunk 3 above)
Comment (jwajgelt) [reply Common/cpp/NativeModules/NativeReanimatedModule.cpp:452]: I think `cleanup` is a better naming here, since the caller doesn't really care what `NativeReanimatedModule` actually needs to do to cleanup.
I'd be more willing to rename the method on `AnimatedSensorModule` to `cleanup` as well, though again, there `unregister` is more consistent with the already present `unregisterSensor`

Comment (tomekzaw) [reply Common/cpp/NativeModules/NativeReanimatedModule.cpp:452]: Ok, let it be.

**Review by tomekzaw — APPROVED** [review]

**Comment by gp3gp3gp3** [comment]
This commit is quite important for our project, since we have to force a reload in production to support RTL languages, and we are seeing a high amount of crashes that I am hoping this should address.

A backport to v2 would be ideal, but we can update our version to 3 if it includes this commit. When can we expect an RC cut with this?

**Comment by tomekzaw** [comment]
Hey @gp3gp3gp3, actually we plan to release 3.0.0 early next week 🤞

**Comment by spsaucier** [comment]
We are not able to upgrade to version 3 due to other dependencies which break with removal of _setGlobalConsole (https://github.com/mrousavy/react-native-vision-camera/issues/1514). A patch to version 2 would be immensely appreciated.
