### PR TITLE
Remove `CellRendererComponent` from Animated.FlatList props

### LINKED ISSUE #5931: CellRendererComponent prop does not work with Animated.Flatlist
### Description

CellRendererComponent prop does not work with Animated.Flatlist

### Steps to reproduce

Use a Animated.FlatList

Put in a CellRendererComponent prop

It wouldn't render on Android

### Snack or a link to a repository

https://snack.expo.dev/wI0E5xWM3_QzmQbwRYnwV

### Reanimated version

3.8.1

### React Native version

0.73

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by Latropos**
## Summary

Closes #5931 

In our implementation of Animated.FlatList we overwrite `CellRendererComponent` and providing it is not supported. Therefore I remove it from valid props

## Error message
Error message should contain the information "CellRendererComponent is not supported in Animated.FlatList"
Code:
image

Error message:
image

## Test plan

Tests in `__typetests__/common/AnimatedComponentTest.tsx` added

### CODE REVIEW

File: src/reanimated2/component/FlatList.tsx [hunk 1]
```diff
@@ -51,6 +51,10 @@ interface ReanimatedFlatListPropsWithLayout<T>
    * Lets you skip entering and exiting animations of FlatList items when on FlatList mount or unmount.
    */
   skipEnteringExitingAnimations?: boolean;
+  /**
+   * CellRendererComponent is not supported in Animated.FlatList
```
Comment (tjzel) [inline src/reanimated2/component/FlatList.tsx:55]:
```suggestion
   * Property `CellRendererComponent` is not supported in `Animated.FlatList`.
```

**Review by tjzel — APPROVED** [review]

**Review by piaskowyk — APPROVED** [review]
Just apply Tomek's comment and we can merge 👍
