### PR TITLE
Fix race condition when ShareableHandle is accessed on multiple threads

### LINKED ISSUE #5660: [3.7.0] Data type not recognized by value unpacker. at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)
### Description

Cannot reproduce it locally, for now I've encountered in production builds on Androids 11,12,13,14. 

Error: 
`Data type not recognized by value unpacker. at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)`

Full stacktrace: 

```
﻿﻿com.facebook.jni.CppException: [Reanimated] Data type not recognized by value unpacker.

Error: [Reanimated] Data type not recognized by value unpacker.
    at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)
        at com.swmansion.reanimated.AndroidUIScheduler.triggerUI(AndroidUIScheduler.java:-2)
        at com.swmansion.reanimated.AndroidUIScheduler$1.run(AndroidUIScheduler.java:24)
        at com.swmansion.reanimated.AndroidUIScheduler$2.runGuarded(AndroidUIScheduler.java:43)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:250)
        at android.app.ActivityThread.main(ActivityThread.java:7755)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

### Steps to reproduce

1. Updated to 3.7.0
2. crashes

### Snack or a link to a repository

no-repo-cannot-reproduce

### Reanimated version

3.7.0

### React Native version

0.73.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

LG G8 ThinQ™ (LM-G820), Mi Note 10, Galaxy S22 Ultra (SM-S908U), moto g(8) power

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by tjzel**
## Summary

Fixes #5660, a regression introduced in #4300.

The aforementioned race condition happens this way:

1. An object using a `ShareableHandle` underneath (e.g. a shared value) is created.
2. This object is accessed on UI thread.
3. The initializer of this `ShareableHandle` get called on the UI thread.
4. At the same time, JS thread schedules an operation on this object (e.g. setting a value of shared value).
5. Access on UI thread forces the initialization. The condition of the if clause resolves to true and UI thread tries to access the runtime.
Screenshot 2024-03-04 at 13 00 07
6. However, access from JS thread has locked the runtime and causes the UI runtime to wait.
7. Then, JS thread enters the same if clause body and initializes the whole shareable.
8. After initializing and releasing the runtime, UI thread gets unblocked.
9. However, now `initializer_` has been nulled and causes memory access issues.

It's difficult to change the whole flow of locking to prevent such scenarios. Therefore we won't null the `initializer_` object anymore. However, this won't fix the problem of potential double initialization. Luckily, the code of `valueUnpacker` already prevents that with its shareable handle cache and the fact that runtime operations must be sequential. 

## Test plan

Run the following race condition reproduction made - you should re-run the app several times (probably up to 20ish) since it's most likely to happen when the app starts. It's also more likely to happen on Android simulators (at least for me).

<details>
<summary>
Test code
</summary>

```tsx
import {useSharedValue} from 'react-native-reanimated';
import {useEffect, useState} from 'react';

const value = 666666;

const Screen = () => {
  const sv = useSharedValue(value);
  useSharedValue(1);
  useSharedValue(2);
  useSharedValue(3);
  sv.value = value;

  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const currentValue = sv.value;
  }, [sv]);

  return null;
};
const ReanimatedCrashReproduction = () => {
  const [render, setRender] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => setRender(r => !r), 500);
    return () => clearInterval(interval);
  }, []);

  return render ? <Screen /> : null;
};

export default ReanimatedCrashReproduction;
```

</summary>

You can do the following to see that double initialization happens still, but all is well 🚰.

Screenshot 2024-03-06 at 10 06 50

Big thanks to @piaskowyk for the debugging help 🚀

### CODE REVIEW

**Comment by Latropos** [comment]
@tjzel I was looking into linked issue and it seemed that the problem was occurring only in newest release. Could you please track down and link here the exact PR causing the bug?

**Comment by callaars** [comment]
@Latropos, it's been occurring since 3.7.1.

**Comment by tomekzaw** [comment]
@Latropos It seems like the offending PR was #4300.

File: Common/cpp/SharedItems/Shareables.cpp [hunk 1]
```diff
@@ -245,13 +246,16 @@ jsi::Value ShareableRemoteFunction::toJSValue(jsi::Runtime &rt) {
...
     auto initObj = initializer_->getJSValue(rt);
-    remoteValue_ =
-        std::make_unique<jsi::Value>(getValueUnpacker(rt).call(rt, initObj));
-    remoteRuntime_ = &rt;
-    initializer_ = nullptr; // we can release ref to initializer as this
-    // method should be called at most once
+    auto value = std::make_unique<jsi::Value>(getValueUnpacker(rt).call(
+        rt, initObj, jsi::String::createFromAscii(rt, "Handle")));
+
+    std::unique_lock<std::mutex> lock(initializationMutex_, std::try_to_lock);
```
Comment (piaskowyk) [inline Common/cpp/SharedItems/Shareables.cpp:254]: Wy need to remove `std::try_to_lock` because this will lead to calling `*remoteValue_` on `null` :/

Comment (tjzel) [reply Common/cpp/SharedItems/Shareables.cpp:254]: smart

**Review by piaskowyk — APPROVED** [review]

**Review by tomekzaw — APPROVED** [review]
