### PR TITLE
Fix scrollTo on FlashList

### LINKED ISSUE #4376: scrollTo not working with FlashList
### Description

I've seen there's been previous work done to accommodate FlashList with Reanimated, but I'm still suffering from an issue when using it myself.

Using scrollTo on an animated reference of a FlashList does nothing, but works fine with a standard FlatList.

The provided test case is quite similar to actual usage in my app, other than I actually use a gesture to set the position.

### Steps to reproduce

Run the provided repository and press the `New Pos` button, or see App.js

### Snack or a link to a repository

https://github.com/QOAL/rnflrepro

### Reanimated version

3.0.2

### React Native version

0.71.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Realme 7 (Global)

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by tomekzaw**
## Summary

Fixes #4376. Analogous to #3988.

Solution: copy the code from `createAnimatedComponent.tsx` to `useAnimatedRef.ts`

https://github.com/software-mansion/react-native-reanimated/blob/87fb9c6a1fb6b8c839b65b90ad16f574f45a1294/src/createAnimatedComponent.tsx#L289-L291

Example:

<details>
<summary>App.tsx</summary>

```tsx
import Animated, {
  runOnUI,
  scrollTo,
  useAnimatedRef,
} from 'react-native-reanimated';
import {Button, StyleSheet, Switch, Text, View} from 'react-native';
import {FlashList} from '@shopify/flash-list';

import React from 'react';

declare const _WORKLET: boolean;

const AnimatedFlashList = Animated.createAnimatedComponent(FlashList);

interface Item {
  label: string;
}

const DATA: Item[] = [...Array(100)].map((_, i) => ({label: String(i)}));

function getRandomOffset() {
  'worklet';
  return Math.random() * 2000;
}

export default function ScrollToExample() {
  const [animated, setAnimated] = React.useState(true);

  const aref = useAnimatedRef<FlashList<Item>>();

  const scrollFromJS = () => {
    console.log(_WORKLET);
    aref.current?.scrollToOffset({offset: getRandomOffset(), animated});
  };

  const scrollFromUI = () => {
    runOnUI(() => {
      'worklet';
      console.log(_WORKLET);
      scrollTo(aref, 0, getRandomOffset(), animated);
    })();
  };

  return (
    <>
      <View style={styles.buttons}>
        <Switch
          value={animated}
          onValueChange={setAnimated}
          style={styles.switch}
        />
        <Button onPress={scrollFromJS} title="Scroll from JS" />
        <Button onPress={scrollFromUI} title="Scroll from UI" />
      </View>
      <AnimatedFlashList
        // @ts-ignore createAnimatedComponent seems to break generic types
        ref={aref}
        data={DATA}
        // @ts-ignore createAnimatedComponent seems to break generic types
        renderItem={({item}: {item: Item}) => (
          <Text key={item.label} style={styles.text}>
            {item.label}
          </Text>
        )}
        estimatedItemSize={200}
      />
    </>
  );
}

const styles = StyleSheet.create({
  switch: {
    marginBottom: 10,
  },
  buttons: {
    marginTop: 80,
    marginBottom: 40,
    alignItems: 'center',
  },
  text: {
    fontSize: 50,
    textAlign: 'center',
  },
});
```

</details>

Before:

Android:

https://user-images.githubusercontent.com/20516055/233322746-637fa2a9-0e93-40ac-baa8-c3c3d2449867.mp4

iOS:

https://user-images.githubusercontent.com/20516055/233322714-20c03ade-1f15-4d76-8a5e-b4b59ebe8a73.mp4

## Test plan

1. Install FlashList in Example app with `yarn add @shopify/flash-list && cd ios && pod install`

2. Paste the attached code snippet into App.tsx

> **Warning**
> It looks like animated refs don't update properly on render. In this case, pressing "Scroll from UI" button after a fast refresh does nothing. Please reload the <kbd>r</kbd> to reload the app and check again.

### CODE REVIEW

File: src/reanimated2/hook/useAnimatedRef.ts [hunk 1]
```diff
@@ -19,15 +23,19 @@ const getTagValueFunction = global._IS_FABRIC
...
 
   if (!ref.current) {
     const fun: RefObjectFunction<T> = <RefObjectFunction<T>>((component) => {
       // enters when ref is set by attaching to a component
       if (component) {
-        tag.value = getTagValueFunction(component);
+        tag.value = getTagValueFunction(
+          component.getScrollableNode
+            ? component.getScrollableNode()
+            : component
```
Comment (piaskowyk) [inline src/reanimated2/hook/useAnimatedRef.ts:37]: Maybe, we could add some comment why we use `.getScrollableNode()` or just add information that it comes from `FlashList`?

Comment (tomekzaw) [reply src/reanimated2/hook/useAnimatedRef.ts:37]: Hopefully `git blame` should find this PR which links to the original issue but yeah you're right, adding a comment here would be nice 😄 Also, there's a similar place in `createAnimatedComponent.tsx` which does exactly the same thing and I'd like to move it to a new utils function, wdyt?

Comment (piaskowyk) [reply src/reanimated2/hook/useAnimatedRef.ts:37]: The idea of a new function sound great ☺️

**Review by piaskowyk — APPROVED** [review]
