### PR TITLE
Fix reparenting

### LINKED ISSUE #7493: Occasional crash on Android when entering animation
### Description

I bootstrapped a new project with [React Native Reusables](https://rnr-docs.vercel.app), which uses react-native-reanimated under the hood, and noticed that the Select component occasionally crashes when being pressed on Android.

Image

As soon as I remove the animations, this doesn't seem to happen anymore, leading me to think it might be caused by react-native-reanimated.

### Steps to reproduce

1. Press the component using animations from react-native-reanimated
2. Crash? If not, try again

### Snack or a link to a repository

https://github.com/benjidotsh/react-native-reanimated-crash

### Reanimated version

3.17.5

### React Native version

0.78.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Host machine

macOS

### Device model

Medium Phone API 35

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by bartlomiejbloniarz**
## Summary

This PR fixes how we manage moving views (through reparenting) during a layout animation. Our current behavior would not change the parent in our animation state, which would cause us to try to apply updates with a stale parent. This would cause a crash, because the view state for the parent would be unavailable.

Hopefully closes #7493 

## Test plan

Check `[LA] Reparenting` example on Android. It should lead to a soft crash in our example app. (In previous RN versions it would be a hard crash)

### CODE REVIEW

File: apps/common-app/src/apps/reanimated/examples/LayoutAnimations/ReparentingExample.tsx [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import React from 'react';
+import { Button, StyleSheet, View } from 'react-native';
+import Animated, { LinearTransition } from 'react-native-reanimated';
+
+export default function ReparentingExample() {
+  const [collapsable, setCollapsable] = React.useState(false);
```
Comment (tomekzaw) [inline apps/common-app/src/apps/reanimated/examples/LayoutAnimations/ReparentingExample.tsx:6]:
```suggestion
  const [collapsable, setCollapsable] = React.useState(false);

```

File: apps/common-app/src/apps/reanimated/examples/LayoutAnimations/ReparentingExample.tsx [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+  return (
+    <View style={styles.container}>
+      <Button
+        title="Toggle Collapsable"
```
Comment (tomekzaw) [inline apps/common-app/src/apps/reanimated/examples/LayoutAnimations/ReparentingExample.tsx]:
```suggestion
        title="Toggle collapsable"
```

File: packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp [hunk 3]
```diff
@@ -6,7 +6,6 @@
 
 #include <set>
 #include <utility>
```
Comment (tomekzaw) [inline packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp]: Restore newline
```suggestion
#include <utility>

```

**Review by tomekzaw — APPROVED** [review]

**Review by piaskowyk — APPROVED** [review]

**Review by tomekzaw — APPROVED** [review]

**Comment by prashanFOMO** [comment]
would be really great to get a release cut after this merges - i believe quite a few of us are waiting for this fix :)

**Comment by kasterlod** [comment]
unfortunately still RetryableMountingLayerException is thrown on production with this code

**Comment by kasterlod** [comment]
with entering animations globally removed there's no RetryableMountingLayerException. Crash is detectable in pre-release report
