### PR TITLE
A better way to handle exceptional situations

### LINKED ISSUE #1253: useAnimatedStyle doesn't allow combining static styles
## Description

The `useAnimatedStyle` hook only works when using purely animated values, so it cannot be used to merge additional static styles (e.g. from `StyleSheet.create`).

E.g.:

#### Doesn't work

```jsx
const headerStyle = useAnimatedStyle(() => [styles.header, { transform: [{ translateY: headerY.value }] }]);
// ...
return <Reanimated.View style={headerStyle} ... />
```

#### Works

```jsx
const headerStyle = useAnimatedStyle(() => ({ transform: [{ translateY: headerY.value }] }));
// ...
return <Reanimated.View style={[styles.header, headerStyle]} ... />
```

With "doesn't work" I mean that the transforms aren't applied at all. The `styles.header` values are correctly applied, but `translateY` just always stays `0`. (Even though the function is executed multiple times, checked with `console.log`!)

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.6

### LINKED ISSUE #1638: AnimatedStop error when animating offset via AnimatedProps
## Description
If you try to animated the offset with 'animatedProps' on a Stop component from 'react-native-svg' created withAnimated.createAnimatedComponent an error appears.

## Steps To Reproduce

1. create a PanGesture with the sliderComponent inside and a cursor

```
 export const SliderComponent: React.FC<{}> = ({}) => {
  const translateX = useSharedValue<number>(0)

  const gestureHandler = useAnimatedGestureHandler<
    PanGestureHandlerGestureEvent,
    { offsetX: number }
  >({
    onActive: ({ translationX }, context) => {
      translateX.value = clamp(
        translationX + context.offsetX,
        0,
        width - HORIZONTAL_PADDING * 2,
      )
    },
    onStart: (_event, context) => {
      context.offsetX = translateX.value
    },
  })

  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: translateX.value }],
    }
  })

  return (
    <View style={styles.container}>
      <PanGestureHandler onGestureEvent={gestureHandler}>
        <Animated.View>
          <Cursor />
          <Slider offset={translateX} />
        </Animated.View>
      </PanGestureHandler>
    </View>
  )
}
```

2. change the offset with an animatedProps 
```
export const Slider: React.FC<SliderProps> = ({ offset }) => {
  const normalizedWidth = width - HORIZONTAL_PADDING * 2

  const props = useAnimatedProps(() => {
    return {
      offset: interpolate(
        translateX.value,
        [0, width - HORIZONTAL_PADDING * 2],
        [0, 1],
      ),
    }
  })

  return (
    <View style={styles.container}>
      <Svg
        width={normalizedWidth}
        height="11"
        viewBox={`0 0 ${normalizedWidth + 3} 11`}
        fill="none">
        <Rect
          x="1"
          y="1"
          width={`${normalizedWidth}`}
          height="9"
          rx="4.5"
          fill="url(#paint0_linear)"
          stroke="white"
          strokeWidth="2"
          strokeLinejoin="bevel"
        />
        <Defs>
          <LinearGradient
            id="paint0_linear"
            x1="0"
            y1="6.00015"
            x2={`${normalizedWidth}`}
            y2="6.00023"
            gradientUnits="userSpaceOnUse">
            <AnimatedStop animatedProps={props} stopColor="#295672" />
            <AnimatedStop animatedProps={props} stopColor="#ED6464" />
          </LinearGradient>
        </Defs>
      </Svg>
    </View>
  )
}
```

3. move the cursor and the error will appear

### Expected behavior

Should just move the cursor and change the offset of the Stop.

### Actual behavior

```
Exception in HostFunction: Value is undefined, expected a number
```

## Package versions

- React: 16.13.1
- React Native: 0.63.1
- React Native Reanimated: 2.0.0-rc.2
- NodeJS: 12.18.0

### PR DESCRIPTION
**Pull request by karol-bisztyga**
### Description

If we wanted to update animated props of a component that renders nothing, an error has to be thrown. Until now, the error message has looked like this: `Exception in HostFunction: Value is undefined, expected a number`. This PR makes it more clear and tells what went wrong.

Fixes #1638 

### Test code and steps to reproduce

```Js
import Animated, {
  useSharedValue,
  useAnimatedProps,
} from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React from 'react';

class MyComp1 extends React.Component {
  constructor (props) {
    super(props);
    console.log('x passed 1', props.x);
  }

  render () {
    return null;
  }
};

class MyComp2 extends React.Component {
  constructor (props) {
    super(props);
    console.log('x passed 2', props.x);
  }

  render () {
    return <View></View>;
  }
};

const Animated1 = Animated.createAnimatedComponent(MyComp1);
const Animated2 = Animated.createAnimatedComponent(MyComp2);

export default function AnimatedStyleUpdateExample(props) {
  const sv = useSharedValue(0);

  const props1 = useAnimatedProps(() => ({ x: sv.value }));
  const props2 = useAnimatedProps(() => ({ x: sv.value*2 }));

  return (
    <View>
      <Button
        title="toggle"
        onPress={() => {
          sv.value = Math.random() * 350;
        }}
      />
      {/* this will break */}
      <Animated1 animatedProps={props1} />
      {/* this will do alright */}
      <Animated2 animatedProps={props2} />
    </View>
  );
}

```

### Description

We don't want to allow returning combined styles from `useAnimatedStyle`. Here a value returned by an updater is being checked on both - initial updater run and UI thread. We only want `useAnimatedStyle` to return an object(array excluded). This PR makes error messages more clear.

Fixes #1253 

### Test code and steps to reproduce

```Js
import Animated, {
  withTiming,
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';
import { View, Button, StyleSheet } from 'react-native';
import React from 'react';

export default function AnimatedStyleUpdateExample() {
  const sv = useSharedValue(0);

  const style = useAnimatedStyle(() => {
    // if (_WORKLET) return 55;
    return [
      {
        width: withTiming(sv.value),
      },
      styles.test,
    ];
  });

  return (
    <View>
      <Animated.View
        style={[
          { width: 100, height: 80, backgroundColor: 'black', margin: 30 },
          style,
        ]}
      />
      <Button
        title="toggle"
        onPress={() => {
          sv.value = Math.random() * 350;
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  test: {
    backgroundColor: 'red',
  },
});

```

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

File: src/reanimated2/Hooks.js [hunk 1]
```diff
@@ -224,6 +237,7 @@ function styleUpdater(
   'worklet';
   const animations = state.animations || {};
   const newValues = updater() || {};
+  validateAnimatedStyles(newValues);
```
Comment (Szymon20000) [inline src/reanimated2/Hooks.js:240]: I think it's enough to check it on RN side during the initial run. Let's not slow down UAS.

Comment (karol-bisztyga) [reply src/reanimated2/Hooks.js:240]: That was my first idea. Then I realized someone could conditionally return an invalid value checking for `_WORKLET`. So I just handled this. I know, however, this is a rare edge case. I'm ok with checking it only on the initial run.

**Review by Szymon20000 — APPROVED** [review]

File: src/reanimated2/Hooks.js (hunk 1 above)
Comment (karol-bisztyga) [reply src/reanimated2/Hooks.js]: fixed f3d2a5e

**Comment by jonmumm** [comment]
Why does an error have to be thrown here? I am trying to do:

```ts
const AnimatedStop = Animated.createAnimatedComponent(Stop);

const MyComponent = () => {
  const firstStopAnimatedProps = useAnimatedProps(() => {
    return {
      stopColor: "white",
    };
  });

  const secondStopAnimatedProps = useAnimatedProps(() => {
    return {
      stopColor: "black",
    };
  });

  return (
    <Svg style={StyleSheet.absoluteFill}>
      <Defs>
        <LinearGradient id="grad" x1="0" y1="0" x2="1" y2="1">
          <AnimatedStop
            offset="0"
            animatedProps={firstStopAnimatedProps}
            stopOpacity="1"
          />
          <AnimatedStop
            offset="1"
            animatedProps={secondStopAnimatedProps}
            stopOpacity="1"
          />
        </LinearGradient>
      </Defs>
      <Rect x="0" y="0" width="100%" height="100%" fill="url(#grad)" />
    </Svg>
  );
};
```

and now it's throwing this "Maybe it renders nothing?" exception. Not sure how to handle this

File: src/createAnimatedComponent.js [hunk 2]
```diff
@@ -253,6 +253,11 @@ export default function createAnimatedComponent(Component) {
       } else {
         // hostInstance can be null for a component that doesn't render anything (render function returns null). Example: svg Stop: https://github.com/react-native-svg/react-native-svg/blob/develop/src/elements/Stop.tsx
         const hostInstance = RNRenderer.findHostInstance_DEPRECATED(this);
+        if (!hostInstance) {
+          throw new Error(
```
Comment (jonmumm) [inline src/createAnimatedComponent.js:257]: This is making using SVG `Stop` animations not work anymore. Simply removing this makes it work for me again, but I don't know if it will break other things

**Comment by karol-bisztyga** [comment]
@jonmumm please read [this](https://github.com/software-mansion/react-native-reanimated/issues/1638#issuecomment-764608442)

**Comment by jonmumm** [comment]
@karol-bisztyga I am trying to animate the `stopColor` on the `Stop`. The example you have [here](https://github.com/software-mansion/react-native-reanimated/issues/1638#issuecomment-764608442) shows how to animate the offset of the stop, but I'm not seeing a way how to animate the color since that seems to have to only be on the Stop itself rather than settable from it's parent.
