### PR TITLE
Fix SSR regression in 2.3.0

### LINKED ISSUE #2621: [Web] `setImmediate` SSR regression in 2.3.0-beta.3
## Description

If you run 2.3.0-beta.3 with Next.js, you get this error:

image

### Expected behavior

`setImmediate` should not be used on Web. Instead, it should use `requestAnimationFrame`. This is a regression from previous versions, where this replacement was already made.

It was originally fixed here: https://github.com/software-mansion/react-native-reanimated/pull/1891

### Actual behavior & steps to reproduce

Create an SSR app, use reanimated 2.3.0-beta.3.

## Snack or minimal code example

I can create one if necessary, but this bug has historically been an issue with Reanimated.

## Package versions

- React Native: 0.64.3
- React Native Reanimated: 2.3.0-beta.3
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

## Patch

This patch fixes it:

```patch
diff --git a/node_modules/react-native-reanimated/lib/reanimated2/ViewDescriptorsSet.js b/node_modules/react-native-reanimated/lib/reanimated2/ViewDescriptorsSet.js
index 2db94aa..3f1d699 100644
--- a/node_modules/react-native-reanimated/lib/reanimated2/ViewDescriptorsSet.js
+++ b/node_modules/react-native-reanimated/lib/reanimated2/ViewDescriptorsSet.js
@@ -1,5 +1,14 @@
 import { useRef } from 'react';
 import { makeMutable } from './core';
+import { Platform } from 'react-native';
+
+let updater
+if (Platform.OS === 'web') {
+  updater = requestAnimationFrame
+} else {
+  updater = setImmediate
+}
+
 export function makeViewDescriptorsSet() {
     const ref = useRef(null);
     if (ref.current === null) {
@@ -18,7 +27,7 @@ export function makeViewDescriptorsSet() {
                 data.items.push(item);
                 if (!data.waitForInsertSync) {
                     data.waitForInsertSync = true;
-                    setImmediate(() => {
+                    updater(() => {
                         data.sharableViewDescriptors.value = data.items;
                         data.waitForInsertSync = false;
                     });
@@ -28,7 +37,7 @@ export function makeViewDescriptorsSet() {
                 data.batchToRemove.add(viewTag);
                 if (!data.waitForRemoveSync) {
                     data.waitForRemoveSync = true;
-                    setImmediate(() => {
+                    updater(() => {
                         const items = [];
                         for (const item of data.items) {
                             if (data.batchToRemove.has(item.tag)) {

```

### PR DESCRIPTION
**Pull request by nandorojo**
Use `requestAnimationFrame` on Web, instead of `setImmediate`.

See #2621 and https://github.com/software-mansion/react-native-reanimated/pull/1521 for reference.

## Description

Fix #2621

## Changes

`setImmediate` breaks SSR on Web. `requestAnimationFrame` is better. This was already discussed and merged previously at #1521.

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by nandorojo** [comment]
CI failing at lint stage, not sure why

File: src/reanimated2/ViewDescriptorsSet.ts [hunk 1]
```diff
@@ -23,6 +24,8 @@ export interface ViewDescriptorsSet {
   ) => void;
 }
 
+const scheduleUpdates: Platform.OS === 'web' ? requestAnimationFrame : setImmediate;
```
Comment (kirillzyusko) [inline src/reanimated2/ViewDescriptorsSet.ts:27]: Shouldn't it be?

```ts
const scheduleUpdates = Platform.OS === 'web' ? requestAnimationFrame : setImmediate;
```

I think it's the reason of failing `eslint`

Comment (nandorojo) [reply src/reanimated2/ViewDescriptorsSet.ts]: I updated it to match this line: https://github.com/DrRefactor/react-native-reanimated/blob/54fb4137ac6697e322d54ece10b1a7a0260d6bfa/src/core/AnimatedNode.js#L79

**Comment by nandorojo** [comment]
CI passed, thanks @kirillzyusko for the pointer.

**Review by piaskowyk — APPROVED** [review]
Thanks! 🚀
