### PR TITLE
cachedMatchers initialization

### LINKED ISSUE #1472: interpolateColor ERROR: Cannot read property 'exec' of undefined
## Description

Trying to animate background color, but got error Cannot read property 'exec' of undefined. Also tried to wrap return value of backgroundColor into processColor function but got  the same result

## Code example:

```

import React, {memo, useMemo, useCallback} from 'react';
import {StyleSheet} from 'react-native';
import Animated, {
	useSharedValue,
	useDerivedValue,
	useAnimatedStyle,
	withTiming,
	interpolateColor,
} from 'react-native-reanimated';
import {TouchableWithoutFeedback} from 'react-native-gesture-handler';

const ENABLED_POSITION = 20;

export const Thumbler = memo(() => {
	const x = useSharedValue(ENABLED_POSITION);
	const enabled = useSharedValue(0);
	const translateX = useDerivedValue(() => x.value * enabled.value);

	const onPress = useCallback(() => {
		enabled.value = withTiming(1, {duration: 100});
	}, []);
	const backgroundColor = useDerivedValue(() => {
		return interpolateColor(enabled.value, [0, 1], ['#333333', '#666999']);
	});
	const useIndicatorStyle = useAnimatedStyle(() => ({
		transform: [{translateX: translateX.value}],
	}));
	const useThumblerStyle = useAnimatedStyle(() => ({
		backgroundColor: backgroundColor.value,
	}));

	const indicatorStyle = useMemo(
		() => [styles.indicator, useIndicatorStyle],
		[useIndicatorStyle],
	);
	const thumblerStyle = useMemo(() => [styles.thumbler, useThumblerStyle], [
		useThumblerStyle,
	]);

	return (
		<TouchableWithoutFeedback onPress={onPress} style={styles.touchable}>
			<Animated.View style={thumblerStyle}>
				<Animated.View style={indicatorStyle} />
			</Animated.View>
		</TouchableWithoutFeedback>
	);
});

const styles = StyleSheet.create({
	touchable: {
		height: 20,
		width: 38,
		justifyContent: 'center',
		alignItems: 'center',
	},
	thumbler: {
		width: 36,
		height: 18,
		borderRadius: 9,
	},
	indicator: {
		width: 18,
		height: 18,
		borderRadius: 20,
		backgroundColor: '#ddd',
	},
});

```

## Package versions:

- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.9.1

### LINKED ISSUE #1478: InterpolateColor fails on Android
```
 const  v = useSharedValue(0);
 const animatedStyle = useAnimatedStyle(() => ({
    backgroundColor: interpolateColor(v.value, [-1, 0, 1], ['red', 'blue', 'green']),
  }));
```
fails with the following on Android:

Screen Shot 2020-11-26 at 10 07 08

### PR DESCRIPTION
**Pull request by piaskowyk**
## Description
cachedMatchers is lazy loaded and it is frozen when the worklet is being created - it means that is blocked to changes, is possible to call getMatchers() when object is freezed then cachedMatchers has no assigned regexs.

Fixes #1472
Fixes #1478

## Changes
- Added eager initialization of cachedMatchers

## Test code and steps to reproduce
<details>
<summary>Problematic code</summary>

```
import React, { Component, useEffect } from 'react';
import { StyleSheet, View, Button } from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
  isColor,
} from 'react-native-reanimated';
export default function Dwa() {
  const vv = useSharedValue(10);
  const stylez = useAnimatedStyle(() => {
    if (vv.value > 20) {
      isColor('123');
    }
    return { height: vv.value };
  });
  return (
    <View style={styles.container}>
      <Button
        title="One"
        onPress={() => {
          vv.value = 40;
        }}
      />
      <Button
        title="Two"
        onPress={() => {
          isColor('blue');
        }}
      />
      <Animated.View style={[styles.box, stylez]} />
    </View>
  );
}
const BOX_SIZE = 100;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  box: {
    width: BOX_SIZE,
    height: BOX_SIZE,
    borderColor: '#F5FCFF',
    alignSelf: 'center',
    backgroundColor: 'plum',
    margin: BOX_SIZE / 2,
  },
});
```

</details>

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

File: src/reanimated2/Colors.js [hunk 1]
```diff
@@ -49,6 +49,10 @@ function getMatchers() {
   }
   return cachedMatchers;
 }
+// cachedMatchers is lazy loaded and it is frozen when worklet is being created,
+// is possible to call getMatchers() when object is freezed then cachedMatchers
```
Comment (karol-bisztyga) [inline src/reanimated2/Colors.js:53]:
```suggestion
// it is possible to call getMatchers() when the object is frozen, then cachedMatchers
```

File: src/reanimated2/Colors.js [hunk 2]
```diff
@@ -49,6 +49,10 @@ function getMatchers() {
...
+// has no assigned regexs
```
Comment (karol-bisztyga) [inline src/reanimated2/Colors.js:54]:
```suggestion
// has no assigned regexes
```

**Review by karol-bisztyga — COMMENTED** [review]
Just little remarks so the comments might look slightly better, apart from this, good job 👍

**Review by karol-bisztyga — APPROVED** [review]
