### PR TITLE
Fix no host instance case

### LINKED ISSUE #1569: createAnimatedComponent with 'Stop' from 'react-native-svg' throws Error
## Description
If you try to do createAnimatedComponent on a Stop component from 'react-native-svg' an error appears.
It works fine if you use Animated.createAnimatedComponent from 'react-native' but than I can not use 'animatedProps' 

## Steps To Reproduce

1. Create an Svg Component like this and try it out:
```
import Svg, { Defs, LinearGradient, Stop } from 'react-native-svg';

import Animated from 'react-native-reanimated';
import React from 'react';
import { View } from 'react-native';

const AnimatedStop = Animated.createAnimatedComponent(Stop);

const TestComponent = () => (
  <View>
    <Svg
      height="20"
      width="20"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
      preserveAspectRatio="none"
    >
      <Defs>
        <LinearGradient
          id="animatedmood"
          x1={20 / 2}
          y1="0"
          x2={20 / 2}
          y2={20}
          gradientUnits="userSpaceOnUse"
        >
          <AnimatedStop />
          <AnimatedStop />
        </LinearGradient>
      </Defs>
    </Svg>
  </View>
);

export default TestComponent;

```

### Expected behavior
Should just work, like with original react-native

### Actual behavior
Than following error shows up: 
```
TypeError: null is not an object (evaluating 'hostInstance._nativeTag')
```

## Package versions

- React: "16.13.1"
- React Native: "0.63.4"
- React Native Reanimated: "2.0.0-rc.0"
- NodeJS: "v12.14.1"

### PR DESCRIPTION
**Pull request by karol-bisztyga**
## Description

This fixes the case when we create an animated component out of a component that does not render anything(render function returns `null`).

An example would be [svg Stop](https://github.com/react-native-svg/react-native-svg/blob/develop/src/elements/Stop.tsx)

Fixes #1569 

<details>
<summary>code example</summary>

```
import Svg, { Defs, Stop, RadialGradient, ClipPath, G, Circle, Ellipse, Rect, Polygon } from 'react-native-svg';

import Animated from 'react-native-reanimated';
import React from 'react';
import { Text } from 'react-native';

const AnimatedStop = Animated.createAnimatedComponent(Stop);

const Test = () => (
  <Svg height="100" width="100">
    <Defs>
      <RadialGradient
        id="grad"
        cx="50%"
        cy="50%"
        rx="50%"
        ry="50%"
        fx="50%"
        fy="50%"
        gradientUnits="userSpaceOnUse">
        <AnimatedStop offset="0%" stopColor="#ff0" stopOpacity="1" />
        <AnimatedStop offset="100%" stopColor="#00f" stopOpacity="1" />
      </RadialGradient>
      <ClipPath id="clip">
        <G scale="0.9" x="10">
          <Circle cx="30" cy="30" r="20" />
          <Ellipse cx="60" cy="70" rx="20" ry="10" />
          <Rect x="65" y="15" width="30" height="30" />
          <Polygon points="20,60 20,80 50,70" />
          <Text
            x="50"
            y="30"
            fontSize="32"
            fonWeight="bold"
            textAnchor="middle"
            scale="1.2">
            Q
          </Text>
        </G>
      </ClipPath>
    </Defs>
    <Rect
      x="0"
      y="0"
      width="100"
      height="100"
      fill="url(#grad)"
      clipPath="url(#clip)"
    />
  </Svg>
);

export default Test;

```

</details>

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

**Review by piaskowyk — APPROVED** [review]

File: src/createAnimatedComponent.js [hunk 1]
```diff
@@ -250,17 +250,18 @@ export default function createAnimatedComponent(Component) {
...
         /**
          * RN uses viewConfig for components for storing different properties of the component(example: https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollViewViewConfig.js#L16).
          * The name we're looking for is in the field named uiViewClassName.
          */
-        viewName = hostInstance.viewConfig?.uiViewClassName;
+        viewName = hostInstance?.viewConfig?.uiViewClassName;
         // update UI props whitelist for this view
         if (this._hasReanimated2Props(styles)) {
-          adaptViewConfig(hostInstance.viewConfig);
+          adaptViewConfig(hostInstance?.viewConfig);
```
Comment (jakub-gonet) [inline src/createAnimatedComponent.js:264]: [This will throw](https://github.com/software-mansion/react-native-reanimated/blob/6990128ef50399004692dce589a88df65bd76418/src/ConfigHelper.js#L134-L135) if you pass an `undefined` here.

File: src/createAnimatedComponent.js [hunk 2]
```diff
@@ -250,17 +250,18 @@ export default function createAnimatedComponent(Component) {
         viewTag = findNodeHandle(this);
         viewName = null;
       } else {
+        // hostInstance can be null for a component that doesn't render anything (render function returns null). Example: svg Stop: https://github.com/react-native-svg/react-native-svg/blob/develop/src/elements/Stop.tsx
         const hostInstance = RNRenderer.findHostInstance_DEPRECATED(this);
         // we can access view tag in the same way it's accessed here https://github.com/facebook/react/blob/e3f4eb7272d4ca0ee49f27577156b57eeb07cf73/packages/react-native-renderer/src/ReactFabric.js#L146
-        viewTag = hostInstance._nativeTag;
+        viewTag = hostInstance?._nativeTag;
```
Comment (jakub-gonet) [inline src/createAnimatedComponent.js:256]: Note: this will make `viewDescriptor.tag = undefined`. I'm not experienced enough with Rea2 to say anything so I'm just mentioning it.

File: src/createAnimatedComponent.js (hunk 1 above)
Comment (karol-bisztyga) [reply src/createAnimatedComponent.js:264]: Yes I know but I don't see an option for it to be undefined

Comment (jakub-gonet) [reply src/createAnimatedComponent.js:264]: Then why we have `?.` here?

Comment (karol-bisztyga) [reply src/createAnimatedComponent.js:264]: this executes only if you attach UAS result to it but maybe there could be a check here to make it safer just in case

Comment (karol-bisztyga) [reply src/createAnimatedComponent.js:264]: hostInstance can be null but not undefined, but the whole expression might be undefined, I misunderstood, sorry

Comment (karol-bisztyga) [reply src/createAnimatedComponent.js]: fixed 9492c29

File: src/createAnimatedComponent.js (hunk 2 above)
Comment (karol-bisztyga) [reply src/createAnimatedComponent.js:256]: I know about that, it is handled by the checks + view descriptor AFAIK only plays a role when you use an animated style which doesn't really make sense when nothing is rendered
