### PR TITLE
[Web] Fix 2589: `null` in `useDerivedValue` 

### LINKED ISSUE #2589: [Web] Can't use `null` inside of `useDerivedValue`
## Description

If you pass `null` as a variable from the JS context to `useDerivedValue`, it breaks on web.

### Expected behavior

`null` should work as a variable in `useDerivedValue`.

### Actual behavior & steps to reproduce

1. Create a variable pointing to `null` in the JS context.
2. Inside of `useDerivedValue`, access that variable.
3. Run it on Web

## Snack or minimal code example

Snack: https://snack.expo.dev/@nandorojo/derived-value-web-issue

Screen Shot 2021-10-31 at 2 31 05 PM

Code:

```tsx
import React from 'react'
import { useDerivedValue } from 'react-native-reanimated'
 
export default function HelloWorld() {
  const broken = null
  useDerivedValue(() => {
    const d = broken
  })
  return <></>
} 
```

To fix it, turn `broken` into 0. Or, comment it out:

Screen Shot 2021-10-31 at 2 31 49 PM

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2.0
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

## Added Context

It works fine on iOS:

image

### PR DESCRIPTION
**Pull request by kkafar**
## Description

Fixes #2589

* https://github.com/software-mansion/react-native-reanimated/issues/2589

## Changes

[`extractMutableFromArray` function](https://github.com/software-mansion/react-native-reanimated/blob/12093cbe04d978b2ef619531755ef7d472242cd9/src/reanimated2/js-reanimated/Mapper.ts#L40) now returns empty array when `array` is `null | undefined`

## Test code and steps to reproduce

Use this code to see that it now works on web:

```tsx
import React from 'react'
import { useDerivedValue } from 'react-native-reanimated'
 
export default function HelloWorld() {
  const broken = null
  useDerivedValue(() => {
    const d = broken
  })
  return (<Text>Test</Text>)
}
```

## Checklist

- [x] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [x] Ensured that CI passes

### CODE REVIEW

File: src/reanimated2/js-reanimated/Mapper.ts [hunk 1]
```diff
@@ -43,7 +43,9 @@ export default class Mapper<T> {
     const res: MutableValue<T>[] = [];
 
     function extractMutables(value: NestedObjectValues<MutableValue<T>>) {
-      if (value instanceof MutableValue) {
+      if (value == null) {
+        // do nothing
```
Comment (piaskowyk) [inline src/reanimated2/js-reanimated/Mapper.ts:47]:
```suggestion
        return;
```

**Review by piaskowyk — CHANGES_REQUESTED** [review]

**Review by piaskowyk — APPROVED** [review]
